const DRUGS = [
  /* ==== HRT-激素類 ==== */
  {
    id:'ev_oral',
    class:'HRT-激素',
    rx:'RX',
    name:'戊酸雌二醇（Estradiol valerate）口服錠',
    aliases:['EV','17β-雌二醇戊酸酯'],
    forms:'口服錠',
    typicalDose:'1–6 mg/日（依醫囑與血中濃度調整）',
    bioavailability:'約 5–10%（口服首過代謝明顯）',
    actions:'原本用於女性更年期雌激素補充、卵巢功能衰竭；跨性別女性 HRT 中用於補充雌激素、抑制 LH/FSH、促進女性第二性徵。',
    indications:'更年期症候群、性別肯定治療（跨女性／非二元）。',
    monitoring:'E2 濃度、肝功能、血脂、凝血風險因子；VTE 風險評估。',
    cautions:'高血栓風險或嚴重肝病需審慎評估；手術前是否停藥依醫囑。',
    interactions:'酵素誘導劑（抗癲癇藥、利福平等）可降低濃度。',
    sideEffects:'胃口不適/噁心、乳房脹痛、頭痛或偏頭痛、情緒波動、水腫/體液滯留、三酸甘油脂上升、輕度血壓變化；口服因首渡效應，靜脈血栓/肺栓塞風險在高危族群更需評估。',
    refs:[{name:'Endocrine Society 2017', url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },
  {
    id:'ev_inj',
    class:'HRT-激素',
    rx:'RX',
    name:'戊酸雌二醇（Estradiol valerate）注射劑',
    aliases:['EV','17β-雌二醇戊酸酯'],
    forms:'肌肉注射',
    typicalDose:'5–20 mg 每 1–2 週（依醫囑與濃度調整）',
    bioavailability:'近乎 100%（肌注）',
    actions:'原本用於雌激素替代治療；跨性別女性 HRT 中提供穩定雌激素濃度，抑制睪固酮、促進女性第二性徵。',
    indications:'更年期症候群、卵巢功能衰竭、性別肯定治療。',
    monitoring:'E2 濃度、肝功能、血脂、凝血因子。',
    cautions:'與口服相比峰值較高，需避免過高劑量引發副作用。',
    interactions:'酵素誘導劑對肌注影響小。',
    sideEffects:'注射部位疼痛/硬結、週期性濃度峰值相關不適（潮熱、頭痛、情緒起伏）、乳房脹痛、水腫；全身性與雌激素相同（VTE 風險仍需評估，但較少首渡肝效應）。',
    refs:[{name:'Endocrine Society 2017', url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },
  {
    id:'micronized_prog',
    class:'HRT-激素',
    rx:'RX',
    name:'微粒化黃體酮（Micronized progesterone）口服膠囊',
    aliases:['天然黃體酮'],
    forms:'口服/陰道膠囊',
    typicalDose:'100–200 mg 睡前（依醫囑）',
    bioavailability:'約 10%（口服，首過代謝高）',
    actions:'原本用於黃體不足、不孕治療；跨性別女性 HRT 中可能改善乳腺發育、助眠、情緒穩定（證據有限）。',
    indications:'黃體不足、不孕治療、部分跨性別輔助療程。',
    monitoring:'嗜睡、頭暈；與鎮靜藥併用留意。',
    cautions:'肝功能不良需評估；嗜睡者建議睡前服用。',
    interactions:'鎮靜安眠藥會增加嗜睡風險。',
    sideEffects:'嗜睡、頭暈、夢境生動/翌日賴床、情緒低落或易怒、乳房脹痛、水腫、頭痛；少數人胃口不適。',
    refs:[{name:'UCSF TransCare', url:'https://transcare.ucsf.edu/guidelines'}]
  },
{
  id:'drospirenone_ethinylestradiol',
  class:['HRT-激素','HRT-抗雄'],  // ← 多分類
  rx:'RX',
  name:'屈螺酮／炔雌醇（Drospirenone / Ethinylestradiol）口服錠',
  aliases:['屈螺酮＋炔雌醇','DRSP/EE','Drospirenone + EE','避孕藥複方'],
  forms:'口服錠',
  typicalDose:'每日 1 錠（多為 21/7 或 24/4 方案，依品項與醫囑）',
  bioavailability:'EE：~38–48%（口服，首渡代謝明顯）；DRSP：~76–85%',
  actions:'原本用於避孕與經前症候群；DRSP 具抗雄性與輕度利尿（抗醛固酮），EE 為合成雌激素。跨性別女性中可作為雌激素補充與抗雄輔助（多為離標籤、需評估風險）。',
  indications:'口服避孕；部分場合作為跨女性之輔助雌激素/抗雄（離標籤）。',
  monitoring:'血壓、血栓風險因子、鉀離子（特別合併保鉀藥時）、肝功能、頭痛/偏頭痛史。',
  cautions:'含 EE 的複方相較 17β-雌二醇製劑具較高 VTE 風險；吸菸且年齡≥35 歲禁忌。腎功能差或合併螺內酯/ACEI/ARB 需留意高鉀。',
  interactions:'CYP3A4 誘導劑（如某些抗癲癇藥、利福平）可降低療效；與含鉀利尿劑/保鉀藥合用可能升高血鉀；與抗凝藥需評估出血/血栓風險。',
  sideEffects:'噁心、乳房脹痛、頭痛/偏頭痛、情緒波動、點滴出血、血壓上升；VTE 風險增加（特別具危險因子者）。DRSP 成分可能導致高鉀（心悸、乏力）。',
  refs:[
    {name:'產品仿單（各品牌）', url:'#'},
    {name:'UCSF TransCare', url:'https://transcare.ucsf.edu/guidelines'}
  ]
},
  /* ==== HRT-抗雄類 ==== */
  {
    id:'spironolactone',
    class:'HRT-抗雄',
    rx:'RX',
    name:'螺內酯（Spironolactone）口服錠',
    aliases:['安體舒通'],
    forms:'口服錠',
    typicalDose:'50–200 mg/日（依血鉀與效果調整）',
    bioavailability:'約 60–90%',
    actions:'原本為利尿降壓藥（醛固酮拮抗）；跨性別女性 HRT 中抑制雄激素作用與分泌。',
    indications:'高血壓、心衰、水腫；跨性別抗雄。',
    monitoring:'血鉀、腎功能、血壓。',
    cautions:'腎功能不全或高鉀禁用。',
    interactions:'保鉀利尿劑、ACEI/ARB、NSAIDs 增加高鉀風險。',
    sideEffects:'多尿、低血壓/頭暈、嗜睡、噁心、乳房不適、月經不規則/點滴出血；高血鉀（心悸、乏力、四肢麻木）與腎功能惡化（需監測）。',
    refs:[{name:'UCSF TransCare', url:'https://transcare.ucsf.edu/guidelines'}]
  },
  {
    id:'bicalutamide',
    class:'HRT-抗雄',
    rx:'RX',
    name:'比卡魯胺（Bicalutamide）口服錠',
    aliases:[],
    forms:'口服錠',
    typicalDose:'25–50 mg/日（依醫囑）',
    bioavailability:'幾乎完全吸收',
    actions:'原本用於攝護腺癌（雄激素受體拮抗）；跨性別女性 HRT 中抑制雄激素作用（離標籤使用）。',
    indications:'攝護腺癌、跨性別抗雄（非核准適應症）。',
    monitoring:'肝功能。',
    cautions:'肝毒性風險高，必須定期驗血。',
    interactions:'肝酵素代謝藥物可能影響其濃度。',
    sideEffects:'肝功能異常/黃疸、噁心、潮熱、乳房不適或壓痛、皮疹、疲倦；罕見嚴重肝毒性需立即就醫。',
    refs:[{name:'臨床經驗', url:'#'}]
  },

  /* ==== HRT-阻斷劑 ==== */
  {
    id:'gnrh_analogue',
    class:'HRT-阻斷劑',
    rx:'RX',
    name:'GnRH 類比（亮丙瑞林、曲普瑞林）長效注射',
    aliases:['青春期阻斷劑'],
    forms:'長效肌注',
    typicalDose:'每 1–3 個月注射一次（依醫囑）',
    bioavailability:'接近 100%',
    actions:'原本用於性早熟、荷爾蒙依賴型腫瘤；跨性別女性 HRT 中可抑制睪固酮分泌。',
    indications:'性早熟、乳癌、攝護腺癌、青春期抑制。',
    monitoring:'E2/T 濃度、骨密度、代謝指標。',
    cautions:'長期使用注意骨質疏鬆。',
    interactions:'臨床顯著交互作用少。',
    sideEffects:'潮熱、出汗、性慾下降、情緒波動/易怒、頭痛、注射部位反應；長期可見骨密度下降、關節痠痛。',
    refs:[{name:'Endocrine Society 2017', url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },

  /* ==== 精麻類 ==== */
  {
    id:'sertraline',
    class:'精麻類',
    rx:'RX',
    name:'舍曲林（Sertraline）口服錠',
    aliases:['左洛復'],
    forms:'口服錠',
    typicalDose:'50–200 mg/日（依醫囑）',
    bioavailability:'約 44%',
    actions:'原本用於憂鬱症、焦慮症（SSRI）；跨性別者常用於伴隨焦慮或憂鬱的輔助治療。',
    indications:'憂鬱症、焦慮症、PTSD。',
    monitoring:'情緒變化、自傷念頭、副作用。',
    cautions:'勿與 MAOI 併用；起效需數週。',
    interactions:'與其他血清素增強藥併用有血清素症候群風險。',
    sideEffects:'噁心、腹瀉、食慾改變、失眠或嗜睡、口乾、手抖、初期焦慮短暫惡化、性功能影響；罕見血清素症候群（躁動、發燒、肌強直）。',
    refs:[{name:'臨床處方指南', url:'#'}]
  },
  {
    id:'melatonin',
    class:'精麻類',
    rx:'OTC',
    name:'褪黑激素（Melatonin）口服錠',
    aliases:['退黑激素'],
    forms:'口服錠／滴劑',
    typicalDose:'1–3 mg 睡前（依地區法規）',
    bioavailability:'口服變異大（約 15–30%）',
    actions:'原本用於時差、失眠；跨性別者可能用於改善睡眠品質。',
    indications:'短期失眠、時差反應。',
    monitoring:'白天嗜睡。',
    cautions:'部分國家屬處方藥；孕哺期請詢問醫師。',
    interactions:'與鎮靜藥併用增加嗜睡。',
    sideEffects:'嗜睡、頭暈、頭痛、清晨倦怠、夢境生動/惡夢；偶見胃口或情緒輕度改變。',
    refs:[{name:'產品仿單', url:'#'}]
  },
  {
    id:'psilocybin',
    class:'精麻類',
    rx:'RX',
    name:'裸蓋菇素（Psilocybin）口服膠囊/粉末',
    aliases:['神奇蘑菇活性成分'],
    forms:'口服膠囊/粉末',
    typicalDose:'臨床試驗劑量 10–25 mg（不可自行使用）',
    bioavailability:'約 50%',
    actions:'原本研究用於抗藥性憂鬱症、臨終焦慮；跨性別者可望用於改善嚴重情緒困擾（尚屬研究階段）。',
    indications:'研究中（憂鬱症、焦慮症等）。',
    monitoring:'心理狀態變化；需專業人員監測。',
    cautions:'在大部分國家屬管制物質；不可自行服用。',
    interactions:'與其他致幻劑或精神藥併用風險未知。',
    sideEffects:'感知與情緒顯著改變、焦慮/恐慌、血壓/心率上升、噁心嘔吐；可能誘發或加劇精神症狀—僅限臨床研究監督。',
    refs:[{name:'Johns Hopkins Psychedelic Research', url:'https://hopkinspsychedelic.org/'}]
  },
   {
  id: 'fluvoxamine',
  class: '精麻類',
  rx: 'RX',
  name: '马来酸氟伏沙明（Fluvoxamine Maleate）口服 劑型',
  aliases: ['Fluvoxamine', 'Luvox'],
  forms: '口服錠',
  typicalDose: '50–300 mg/日（依適應症與醫囑調整）',
  bioavailability: '約 50–53%（口服首過代謝後）',
  actions: 'SSRI，抑制血清素再吸收、具 σ-1 受體激動性，提升血清素濃度並具抗焦慮作用',
  indications: '強迫症（OCD）、重性憂鬱症、恐慌症、社交焦慮、PTSD，有研究用於 COVID-19 初期高風險門診以降低惡化',
  monitoring: '情緒改善、焦慮、GI不適、肝功能、以及與 CYP 交互作用的其他藥物效果',
  cautions: '對 CYP1A2 劑量影響大，需注意藥物交互作用；老年或肝功能差需劑量調整；勿與 MAOI 合用',
  interactions: '強抑 CYP1A2、中度抑 CYP2C19、CYP3A4；可增加如奧氮平、苯二氮䓬類代謝物血中濃度，聯合使用需降低劑量；與 SSRIs 聯用可能有血清素症候群風險。',
  sideEffects: '便秘、頭痛、焦慮、易怒、性功能障礙、口乾、睡眠障礙、GI不適，停止用藥易有撤藥症狀；較少心血管不良反應',
  refs: [
    {
      name: 'Clinical Pharmacokinetics of Fluvoxamine (van Harten et al., 1995)',
      url: 'https://pubmed.ncbi.nlm.nih.gov/8846617/'
    },
    {
      name: 'Luvox (Fluvoxamine Maleate) FDA label',
      url: 'https://www.accessdata.fda.gov/drugsatfda_docs/label/2007/021519lbl.pdf'
    },
    {
      name: 'Wikipedia – Fluvoxamine',
      url: 'https://en.wikipedia.org/wiki/Fluvoxamine'
    }
  ]
},
{
  id: 'lithium',
  class: '精麻類',
  rx: 'RX',
  name: '碳酸鋰（Lithium Carbonate）緩釋片',
  aliases: ['Lithium SR', '鋰鹽'],
  forms: '口服錠（緩釋）',
  typicalDose: '400–1200 mg/日，分 1–2 次（依血中濃度與醫囑調整）',
  bioavailability: '近 100%（口服吸收完全，無蛋白結合）',
  actions: '作用機制未完全明確，主要影響鈉、鉀通道與第二信使系統；可穩定情緒，預防躁鬱症躁期與鬱期發作',
  indications: '雙相情感障礙（躁症急性期、維持治療）、重性憂鬱症增效治療、情緒不穩定相關疾病',
  monitoring: '血中鋰濃度（治療範圍 0.6–1.2 mmol/L）、腎功能（BUN/Cr）、甲狀腺功能、電解質；建議初期每週監測，穩定後每 3–6 個月',
  cautions: '治療窗狹窄，需嚴格監測；腎功能不全、高齡、脫水或合併利尿劑、NSAIDs、ACEI/ARB 需謹慎；孕婦禁用（致畸性心臟缺陷風險）',
  interactions: '利尿劑、NSAIDs、ACEI/ARB 可升高鋰濃度並增加中毒風險；咖啡因與茶鹼可能降低鋰濃度；合併抗精神病藥增加錐體外副作用風險',
  sideEffects: '手抖、口渴、多尿、多飲、體重增加、腸胃不適、甲狀腺功能低下；長期使用可能導致腎功能損害；中毒症狀包含嘔吐、震顫、共濟失調、意識混亂，嚴重可致昏迷或死亡',
  refs: [
    {
      name: 'UpToDate – Lithium: Drug Information',
      url: 'https://www.uptodate.com/contents/lithium-drug-information'
    },
  
    {
      name: 'FDA Label – Lithium Carbonate',
      url: 'https://www.accessdata.fda.gov/drugsatfda_docs/label/2018/017812s040lbl.pdf'
    }
  ]
},
  /* ==== HRT-激素（新增）==== */
  {
    id:'progesterone_inj',
    class:'HRT-激素',
    rx:'RX',
    name:'黃體酮（Progesterone）注射液（油劑）',
    aliases:['天然黃體酮 注射劑'],
    forms:'肌肉注射（油劑）',
    typicalDose:'依醫囑；婦產科常見 25–50 mg IM 每 2–3 日。跨性別用途為個別化、證據有限。',
    bioavailability:'接近 100%（IM）',
    actions:'原本用於黃體不足、助孕與月經異常；跨性別女性 HRT 中偶作輔助（睡眠、情緒、乳腺發育之體感，證據有限）。',
    indications:'黃體不足、助孕治療；跨性別治療屬個別化考量。',
    monitoring:'嗜睡、頭暈、注射部位疼痛；肝功能（長期）。',
    cautions:'非首選；油劑注射需無菌操作，避免自行施打；嗜睡者建議夜間使用。',
    interactions:'與鎮靜安眠藥合用增加嗜睡；與某些抗癲癇酵素誘導劑可能降低效力。',
    sideEffects:'注射部位疼痛/硬塊、嗜睡、頭暈、情緒低落、乳房脹痛、水腫；少數人頭痛或皮疹。',
    refs:[{name:'UCSF TransCare', url:'https://transcare.ucsf.edu/guidelines'}]
  },

  /* ==== HRT-抗雄（新增）==== */
  {
    id:'cyproterone_acetate',
    class:'HRT-抗雄',
    rx:'RX',
    name:'醋酸環丙孕酮（Cyproterone acetate, CPA）口服錠',
    aliases:['CPA'],
    forms:'口服錠',
    typicalDose:'12.5–50 mg/日（用最低有效劑量；依醫囑與副作用調整）',
    bioavailability:'約 88–95%',
    actions:'原本為抗雄＋具黃體素作用；跨性別女性 HRT 中抑制睪固酮分泌與作用。',
    indications:'攝護腺相關治療、性慾過強治療；跨性別抗雄（部分地區常用）。',
    monitoring:'肝功能（ALT/AST）、泌乳素、情緒狀態；長期／高累積劑量注意腦膜瘤風險。',
    cautions:'肝毒性、情緒低落、泌乳素升高；高累積劑量與腦膜瘤風險關聯，需定期追蹤、評估停藥或降劑量。',
    interactions:'與肝臟酵素相關藥物交互作用；與其他致嗜睡藥合用需小心。',
    sideEffects:'嗜睡/倦怠、情緒低落、性慾下降、體重上升、泌乳素升高、肝功能異常；長期或高累積劑量與腦膜瘤風險相關（需定期追蹤）。',
    refs:[{name:'歐洲藥管局安全通報（CPA 與腦膜瘤）', url:'#'}]
  },

  /* ==== 精麻類（新增）==== */
  {
    id:'lidocaine_hcl_inj',
    class:'精麻類',
    rx:'RX',
    name:'鹽酸利多卡因（Lidocaine HCl）注射液',
    aliases:['局部麻醉劑'],
    forms:'浸潤/神經阻滯注射（常見 0.5% / 1% / 2%）',
    typicalDose:'臨床人員操作。最大劑量（保守值）：不含腎上腺素 ≤ 4.5 mg/kg（上限約 300 mg）；含腎上腺素 ≤ 7 mg/kg（上限約 500 mg）。',
    bioavailability:'局部注射以局麻為主；系統性吸收視部位/血流而異',
    actions:'原本用於小手術/縫合/牙科之局部麻醉；不具精神治療適應症。',
    indications:'局部麻醉、神經阻滯、抗心律不整（靜注需加護監測）。',
    monitoring:'注射時觀察毒性：口唇麻、耳鳴、意識混亂、抽搐、心律異常；需備脂肪乳應急。',
    cautions:'務必由醫療專業人員操作，嚴禁自行注射；末梢血供差的部位避免與腎上腺素併用。',
    interactions:'與其他局麻藥或抗心律藥物併用增加毒性風險。',
    sideEffects:'局麻毒性：口唇/舌麻、金屬味、耳鳴、頭暈、抽搐、意識混亂、心律異常；嚴重者可呼吸抑制/心搏停止（必須由醫療人員操作）。',
    refs:[{name:'臨床麻醉學參考', url:'#'}]
  },
  {
    id:'alprazolam',
    class:'精麻類',
    rx:'RX',
    name:'阿普唑仑（Alprazolam）口服錠',
    aliases:['Xanax','苯二氮䓬'],
    forms:'口服錠/OD 錠',
    typicalDose:'0.25–1 mg，每日 2–3 次（短期、最低有效劑量；依醫囑）',
    bioavailability:'約 80–90%',
    actions:'原本用於焦慮/恐慌障礙（BZD）；跨性別族群若合併焦慮，可由精神科短期使用。',
    indications:'焦慮症、恐慌症（短期）。',
    monitoring:'嗜睡、認知影響、跌倒風險；評估依賴/離斷症狀。',
    cautions:'有依賴與離斷風險，勿自行增減/停藥；避免酒精與其他中樞抑制劑。',
    interactions:'與酒精、鴉片類、鎮靜安眠藥合用會疊加呼吸抑制風險。',
    sideEffects:'嗜睡、頭暈、記憶力與反應下降、共濟不良；依賴與離斷症狀（反跳焦慮、失眠）；與酒精或鴉片類併用可致呼吸抑制。',
    refs:[{name:'精神藥理學指引', url:'#'}]
  },

  {
    id:'estradiol_benzoate_inj',
    class:'HRT-激素',
    rx:'RX',
    name:'苯甲酸雌二醇（Estradiol benzoate, EB）注射液',
    aliases:['EB','17β-雌二醇苯甲酸酯'],
    forms:'肌肉注射（油劑）',
    typicalDose:'5–10 mg IM 每 3–7 日一次（依醫囑調整；跨性別 HRT 多用較低頻高穩定方案）',
    bioavailability:'接近 100%（IM）',
    actions:'原本用於雌激素缺乏（更年期症狀、卵巢切除後等）；跨性別女性 HRT 中補充雌激素，促進女性第二性徵並抑制 LH/FSH。',
    indications:'雌激素缺乏、更年期症狀、卵巢切除後治療；跨性別女性/非二元者 HRT。',
    monitoring:'E2、肝功能、血脂、凝血風險因子；注射部位觀察。',
    cautions:'有血栓風險者需謹慎；手術前是否停藥依醫囑。',
    interactions:'酵素誘導劑（如部分抗癲癇藥、利福平）可能降低血中濃度。',
    sideEffects:'注射部位疼痛/硬結、乳房脹痛、頭痛、潮熱、水腫；整體雌激素相關風險仍含 VTE（需評估個人危險因子）。',
    refs:[{name:'Endocrine Society Guideline', url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },
  {
    id:'estradiol_oral_sg',
    class:'HRT-激素',
    rx:'RX',
    name:'雌二醇（Estradiol）口服錠',
    aliases:['E2','17β-雌二醇'],
    forms:'口服錠',
    typicalDose:'1–4 mg/日，分 1–2 次（跨性別 HRT 劑量依醫囑調整）',
    bioavailability:'約 5%（口服；肝臟首渡效應明顯）',
    actions:'原本用於更年期症狀、卵巢功能減退等雌激素缺乏；跨性別女性 HRT 補充雌激素並抑制 LH/FSH，促進女性第二性徵。',
    indications:'更年期症狀、卵巢切除後雌激素補充；跨性別女性/非二元者 HRT。',
    monitoring:'E2、肝功能、血脂；留意血栓風險因子。',
    cautions:'肝功能差、高血栓風險者需審慎使用；注意劑量與首渡效應。',
    interactions:'酵素誘導劑（部分抗癲癇藥、利福平等）可能降低血中濃度。',
    sideEffects:'胃腸不適、乳房脹痛、頭痛、情緒波動、水腫、血脂（特別 TG）上升；口服因首渡效應，VTE 風險在高危族群更需注意。',
    refs:[{name:'新加坡 HSA 藥品資料庫', url:'https://www.hsa.gov.sg/' }]
  },

  /* ==== HRT－雄激素（FTM/跨男性/指定女性出生的非二元者）==== */
  {
    id:'testosterone_enanthate_im',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮庚酸酯（Testosterone enanthate）注射液',
    aliases:['TE','庚酸睪酮'],
    forms:'肌肉注射（油劑）',
    typicalDose:'50–100 mg IM 每週 或 100–200 mg IM 每 2 週（依醫囑與濃度調整）',
    bioavailability:'≈100%（IM）',
    actions:'原適應症為男性性腺機能低下的睪固酮替代；跨男性 HRT 提供生理範圍 T 值，促進男性第二性徵（聲變低、毛髮增多、肌量↑），抑制月經。',
    indications:'男性性腺機能低下；跨男性/指定女性出生之非二元者之性別肯定治療。',
    monitoring:'總/游離 T（注射谷/峰）、血比容/血紅素、脂質、肝腎功能、血壓；依需要追蹤月經抑制與情緒/痤瘡。',
    cautions:'紅血球增多症風險（血比容＞54% 需處置/調整劑量）；痤瘡、掉髮、睡眠呼吸中止症惡化、情緒起伏；孕期禁用。',
    interactions:'與華法林等抗凝劑可能交互影響；與糖皮質激素/利尿劑併用留意水腫。',
    sideEffects:'痤瘡/皮脂增多、多毛、體味改變、聲音變低（不可逆）、性慾變化、注射部位痛；紅血球/血比容上升、水腫、情緒起伏/易怒、脫髮；睡眠呼吸中止症惡化。',
    refs:[{name:'Endocrine Society 2017', url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },
  {
    id:'testosterone_cypionate_im',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮環戊丙酸酯（Testosterone cypionate）注射液',
    aliases:['TC','環戊丙酸睪酮'],
    forms:'肌肉注射（油劑）',
    typicalDose:'50–100 mg IM 每週 或 100–200 mg IM 每 2 週',
    bioavailability:'≈100%（IM）',
    actions:'與 TE 類似之長效酯；跨男性 HRT 維持生理 T 值、誘導男性化改變。',
    indications:'男性性腺機能低下；跨男性 HRT。',
    monitoring:'同 TE。',
    cautions:'同 TE；部分人對溶媒（棉籽油/苄醇等）敏感需留意。',
    interactions:'同 TE。',
    sideEffects:'同 TE：痤瘡、多毛、紅血球增多、情緒起伏、脫髮、注射部位反應；少數人對溶媒成分（如棉籽油/苄醇）敏感。',
    refs:[{name:'WPATH/處方慣例彙整', url:'https://www.wpath.org'}]
  },
  {
    id:'testosterone_undecanoate_depot',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮十一酸酯（Testosterone undecanoate）長效肌注',
    aliases:['TU depot','Nebido® 等'],
    forms:'深部肌注（油劑，長效）',
    typicalDose:'1000 mg IM 起始後 6 週再打一針，之後每 10–14 週（依濃度與症狀調整）',
    bioavailability:'≈100%（IM）',
    actions:'極長效釋放維持穩定 T；跨男性 HRT 可減少濃度波動與針次。',
    indications:'男性性腺機能低下；跨男性 HRT。',
    monitoring:'與其他注射型相同；注意峰值期紅血球上升。',
    cautions:'注射量大需深部肌注；油栓風險極低但需遵循給藥規範；孕期禁用。',
    interactions:'同類雄激素製劑相近。',
    sideEffects:'同類雄激素副作用；注射量大需深部肌注，極罕見油栓/過敏反應（依投藥規範監測）。',
    refs:[{name:'製品仿單/臨床經驗', url:'#'}]
  },
  {
    id:'testosterone_gel_1pct',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮凝膠 1%（Transdermal gel）',
    aliases:['Testogel®/AndroGel®（依地區品牌）'],
    forms:'外用凝膠（每日塗抹）',
    typicalDose:'50–100 mg（以原藥量計）QD 外用；依血中 T 調整',
    bioavailability:'約 10–15%（經皮）',
    actions:'原為男性性腺機能低下替代；跨男性 HRT 維持較平穩 T，避免注射峰谷差。',
    indications:'男性性腺機能低下；跨男性 HRT。',
    monitoring:'血中 T（塗抹後 2–8 小時抽血較一致）、血比容/血紅素、肝腎功能、脂質；避免皮膚轉移污染家人。',
    cautions:'塗抹區乾燥後再接觸他人；避免接觸女性/孩童；易燃溶劑遠離火源；孕期禁用。',
    interactions:'經皮系統性交互作用較少；與外用類固醇並用時留意皮膚刺激。',
    sideEffects:'局部皮膚刺激/紅癢、痤瘡、多毛；紅血球增多；藥物轉移污染他人風險（接觸女性/孩童後可致不良反應）。',
    refs:[{name:'UCSF TransCare', url:'https://transcare.ucsf.edu/guidelines'}]
  },
  {
    id:'testosterone_patch',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮貼片（Transdermal patch）',
    aliases:[],
    forms:'經皮貼片（晚間貼、隔日換或每日換，依品項）',
    typicalDose:'2.5–7.5 mg/24h（可多片併用以達標）',
    bioavailability:'受貼片設計影響（持續釋放）',
    actions:'原為男性低 T 替代；跨男性 HRT 提供平穩 T。',
    indications:'男性性腺機能低下；跨男性 HRT（對凝膠不耐或偏好貼片者）。',
    monitoring:'同經皮製劑；留意貼附性與皮膚刺激。',
    cautions:'皮膚刺激/接觸性皮炎；黏貼位置需輪替。',
    interactions:'系統性交互作用少。',
    sideEffects:'貼片處紅斑/刺激/接觸性皮炎、瘙癢或脫落；全身性副作用同其他雄激素（痤瘡、多毛、紅血球增多等）。',
    refs:[{name:'產品仿單', url:'#'}]
  },
  {
    id:'testosterone_undecanoate_oral',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮十一酸酯口服膠囊（Oral TU）',
    aliases:['Andriol®/Jatenzo®（配方差異）'],
    forms:'口服膠囊（需與餐/高脂膳食同服）',
    typicalDose:'依配方 80–237 mg BID（Jatenzo®）或依仿單調整',
    bioavailability:'高度受餐脂影響（變異大）',
    actions:'原為低 T 替代；跨男性 HRT 可用但血中濃度變異較大、肝指數與血壓需留意。',
    indications:'男性性腺機能低下；跨男性 HRT（次選）。',
    monitoring:'血中 T、肝功能、血壓、血比容。',
    cautions:'生體可用率變動大；部分配方與高脂餐同服才穩；孕期禁用。',
    interactions:'與強誘導/抑制 CYP 或 P-gp 藥物可能影響濃度；與脂溶性藥物共同影響吸收。',
    sideEffects:'血壓上升（部分配方有警示）、肝功能指數升高、胃腸不適、頭痛、痤瘡、紅血球增多；濃度變異較大。',
    refs:[{name:'處方資料與臨床經驗', url:'#'}]
  },

  /* ==== 經皮雌激素 ==== */
  {
    id:'estradiol_patch',
    class:'HRT-激素',
    rx:'RX',
    name:'雌二醇貼片（Estradiol transdermal patch）',
    aliases:['17β-雌二醇貼片'],
    forms:'經皮貼片',
    typicalDose:'常見 25–100 μg/日（每週更換 1–2 次，依醫囑）',
    bioavailability:'~90%（避開首渡代謝）',
    actions:'原本用於治療停經後雌激素不足；跨性別女性作為主要雌激素補充，促進女性第二性徵並抑制睪固酮。',
    indications:'更年期症狀、骨質疏鬆預防、跨女性/非二元 HRT。',
    monitoring:'E2 濃度、肝功能、血脂、皮膚反應。',
    cautions:'避免貼在受損皮膚；貼片可能引起皮膚過敏。',
    interactions:'酵素誘導劑影響較小；與抗凝藥併用留意出血風險。',
    sideEffects:'貼附處紅斑、搔癢、刺激或接觸性皮炎；乳房脹痛、頭痛、輕度水腫；相較口服，對肝脂質與凝血的影響較小但 VTE 風險仍需個別評估。',
    refs:[{name:'Endocrine Society 2017', url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },
  {
    id:'estradiol_gel',
    class:'HRT-激素',
    rx:'RX',
    name:'雌二醇凝膠（Estradiol gel）',
    aliases:['17β-雌二醇凝膠'],
    forms:'經皮凝膠',
    typicalDose:'0.75–3 mg E2 含量/日（依醫囑塗抹）',
    bioavailability:'~82%（避開首渡代謝）',
    actions:'原本用於更年期雌激素替代；跨性別女性作為經皮雌激素選擇之一，血中濃度平穩。',
    indications:'更年期症狀、骨質疏鬆預防、跨女性/非二元 HRT。',
    monitoring:'E2、肝功能、血脂；觀察皮膚刺激。',
    cautions:'塗抹部位需乾燥；避免與他人皮膚接觸。',
    interactions:'與其他外用藥併用可能影響吸收率。',
    sideEffects:'塗抹處紅癢/刺激、輕度乾燥；乳房脹痛、頭痛、輕度水腫；若未待乾燥即接觸他人，可能造成藥物轉移。',
    refs:[{name:'UCSF TransCare', url:'https://transcare.ucsf.edu/guidelines'}]
  },
  {
    id:'estradiol_spray',
    class:'HRT-激素',
    rx:'RX',
    name:'雌二醇經皮噴霧（Estradiol spray）',
    aliases:['17β-雌二醇噴霧'],
    forms:'經皮噴霧劑',
    typicalDose:'1–3 噴/日（每噴含約 1.53 mg E2，依醫囑）',
    bioavailability:'~85%（避開首渡代謝）',
    actions:'原本用於更年期雌激素補充；跨性別女性可作為經皮給藥選擇，方便控制劑量。',
    indications:'更年期症狀、骨質疏鬆預防、跨女性/非二元 HRT。',
    monitoring:'E2 濃度、肝功能、皮膚反應。',
    cautions:'避免接觸眼睛與黏膜；塗抹後需等待乾燥。',
    interactions:'與其他外用製劑併用需間隔時間。',
    sideEffects:'局部刺激/紅斑、乾燥或灼熱感；乳房脹痛、頭痛；若未乾燥即接觸他人皮膚，可能導致藥物轉移。',
    refs:[{name:'產品仿單', url:'#'}]
  },
  /* ==== HRT-抗雄（5α-還原酶抑制劑）==== */
{
  id:'finasteride_1mg',
  class:'HRT-抗雄',
  rx:'RX',
  name:'非那雄胺 1 mg（Finasteride）口服錠',
  aliases:['Fina','1 mg 劑型'],
  forms:'口服錠',
  typicalDose:'1 mg QD（多用於雄性禿；跨女性常作輔助降 DHT）',
  bioavailability:'約 65%',
  actions:'5α-還原酶 II 型抑制劑，降低睪固酮轉為 DHT；跨女性 HRT 可作輔助以減少頭皮/體毛 DHT 作用（單用對總睪固酮抑制有限）。',
  indications:'雄性禿；跨女性/非二元者作 DHT 降低之輔助（離標籤使用）。',
  monitoring:'PSA（會下降約 50%，解讀需校正）、毛髮變化、性功能與情緒評估。',
  cautions:'孕婦/可孕者避免接觸碎片粉末（致畸胎風險）；性功能與情緒變化少數報告需留意。',
  interactions:'與無明顯嚴重交互作用為主；合併其他降 PSA 藥物時解讀 PSA 更需小心。',
  sideEffects:'性慾降低、勃起/射精困難、精液量減少、乳房不適或腫塊（罕見）、皮疹；少數人報告情緒低落/焦慮。',
  refs:[{name:'產品仿單 / 臨床經驗', url:'#'}]
},
{
  id:'finasteride_5mg',
  class:'HRT-抗雄',
  rx:'RX',
  name:'非那雄胺 5 mg（Finasteride）口服錠',
  aliases:['Fina','5 mg 劑型'],
  forms:'口服錠',
  typicalDose:'5 mg QD（原適應症前列腺肥大；跨性別用途依醫囑個別化）',
  bioavailability:'約 65%',
  actions:'同上，劑量較高；臨床對毛髮影響與 1 mg 類似，前列腺體積影響較明顯。',
  indications:'良性前列腺肥大；（離標籤）跨性別 DHT 輔助抑制。',
  monitoring:'PSA、泌尿症狀、性功能/情緒變化。',
  cautions:'同 1 mg；長期使用需與醫師討論風險效益。',
  interactions:'同 1 mg。',
  sideEffects:'同 1 mg；偶見頭暈、疲倦。',
  refs:[{name:'產品仿單 / 臨床經驗', url:'#'}]
},
{
  id:'dutasteride_0_5mg',
  class:'HRT-抗雄',
  rx:'RX',
  name:'度他雄胺 0.5 mg（Dutasteride）軟膠囊',
  aliases:['Duta'],
  forms:'口服軟膠囊',
  typicalDose:'0.5 mg QD',
  bioavailability:'約 60%',
  actions:'5α-還原酶 I/II 型皆抑制，DHT 降幅較非那雄胺大；跨女性可作 DHT 輔助抑制（單用對總睪固酮抑制有限）。',
  indications:'良性前列腺肥大；（離標籤）雄性禿、跨性別 DHT 輔助抑制。',
  monitoring:'PSA（顯著下降，解讀需校正）、肝功能（少數）、性功能/情緒評估。',
  cautions:'孕婦/可孕者避免接觸內容物；半衰期長（約 5 週），停藥後作用消退較慢。',
  interactions:'CYP3A4 強抑制劑可能增加其濃度（理論上）。',
  sideEffects:'性慾降低、勃起/射精困難、乳房不適、皮疹；偶見頭暈、胃口不適；少數報告情緒低落。',
  refs:[{name:'產品仿單 / 臨床經驗', url:'#'}]
},

/* ==== HRT－激素（其他劑型補充）==== */
{
  id:'testosterone_nasal_gel',
  class:'HRT－激素',
  rx:'RX',
  name:'睪固酮鼻用凝膠（Transdermal nasal gel）',
  aliases:['鼻用 T 凝膠'],
  forms:'鼻腔凝膠',
  typicalDose:'一側鼻孔 1 次量 x 兩側，每日 2–3 次（依品項，總日劑量約 22–33 mg 原藥）',
  bioavailability:'經鼻吸收（避免首渡；短時峰谷，需多次給藥）',
  actions:'男性低 T 替代；跨男性 HRT 可用於偏好非注射且不適合經皮軟膏者，血中 T 波動較頻繁。',
  indications:'男性性腺機能低下；跨男性/AFAB 非二元者 HRT（個別化）。',
  monitoring:'血中 T（給藥後 1–2 小時抽血以評估峰值區間）、血比容/血紅素、血壓、肝腎功能、脂質。',
  cautions:'鼻黏膜刺激/鼻炎史者謹慎；需固定時段分次使用以減波動；孕期禁用。',
  interactions:'鼻用局部製劑同用可能影響吸收。',
  sideEffects:'鼻黏膜刺激、流鼻水/結痂、頭痛；系統性仍可能出現痤瘡、多毛、紅血球增多、情緒起伏等。',
  refs:[{name:'產品仿單 / 臨床經驗', url:'#'}]
},
{
  id:'testosterone_pellet_implant',
  class:'HRT－激素',
  rx:'RX',
  name:'睪固酮皮下植入丸（Pellet implant）',
  aliases:['Testopel® 等'],
  forms:'皮下植入（每顆常見 75 mg）',
  typicalDose:'總量 450–900 mg 每 3–6 個月（依濃度與症狀調整）',
  bioavailability:'持續釋放（近乎 100%）',
  actions:'長期緩釋維持較平穩 T；跨男性 HRT 可減少注射頻率與濃度波動。',
  indications:'男性性腺機能低下；跨男性 HRT（取決於地區可近性）。',
  monitoring:'血中 T（植入後 4–6 週與之後週期性監測）、血比容/血紅素、脂質、肝腎功能。',
  cautions:'需小手術植入；移位/擠出與感染風險低但存在；孕期禁用。',
  interactions:'系統性交互作用與其他 T 類似。',
  sideEffects:'局部瘀青/疼痛/感染、植入物擠出；系統性：痤瘡、多毛、紅血球增多、水腫、情緒變化、脫髮等。',
  refs:[{name:'產品仿單 / 臨床經驗', url:'#'}]
},
{
  id:'testosterone_sc_autoinject',
  class:'HRT－激素',
  rx:'RX',
  name:'睪固酮庚酸酯週投自動注射（SC auto-injector）',
  aliases:['週投皮下注射 T'],
  forms:'皮下注射（預充填自動注射筆）',
  typicalDose:'50 / 75 / 100 mg SC 每週（依濃度與症狀調整）',
  bioavailability:'≈100%（SC）',
  actions:'與 IM 注射相似；皮下固定每週給藥，濃度較平穩、操作便利。',
  indications:'男性性腺機能低下；跨男性 HRT。',
  monitoring:'血中 T（谷/峰）、血比容/血紅素、血壓、脂質、肝腎功能；注射部位反應。',
  cautions:'避免於皮膚感染/疤痕區注射；孕期禁用。',
  interactions:'與抗凝劑並用需留意注射處出血；其他同類雄激素相近。',
  sideEffects:'注射處紅腫/硬塊、痤瘡、多毛、紅血球增多、水腫、情緒起伏、頭痛；少數人血壓上升。',
  refs:[{name:'產品仿單 / 臨床經驗', url:'#'}]
}
];