const DRUGS = [
  /* ==== HRT-激素類 ==== */
  {
    id:'ev_oral',
    class:'HRT-激素',
    rx:'RX',
    name:'戊酸雌二醇（Estradiol valerate）口服錠',
    aliases:['EV','17β-雌二醇戊酸酯'],
    forms:'口服錠',
    typicalDose:'1–6 mg/日（依醫囑與血中濃度調整）',
    bioavailability:'約 5–10%（口服首過代謝明顯）',
    metabolism:'肝臟酯酶→E2；CYP3A4/1A2/2C9/2C19 部分代謝，並經 UGT1A1/1A3 葡萄醣醛酸化；腸肝循環顯著，腎/膽排泄。',
    enzymeInhibition:'自身無臨床顯著 CYP/UGT 抑制；作為 CYP3A4/UGT 受質，強誘導劑↓濃度、強抑制劑↑濃度。',
    halfLife:'母體 E2 ~1–2 小時；口服酯化物與循環代謝使表觀作用時間延長（數小時至 1 天）。',
    actions:'原本用於女性更年期雌激素補充、卵巢功能衰竭；跨性別女性 HRT 中用於補充雌激素、抑制 LH/FSH、促進女性第二性徵。',
    indications:'更年期症候群、性別肯定治療（跨女性／非二元）。',
    monitoring:'E2 濃度、肝功能、血脂、凝血風險因子；VTE 風險評估。',
    cautions:'高血栓風險或嚴重肝病需審慎評估；手術前是否停藥依醫囑。',
    interactions:'酵素誘導劑（抗癲癇藥、利福平等）可降低濃度。',
    sideEffects:'胃口不適/噁心、乳房脹痛、頭痛或偏頭痛、情緒波動、水腫/體液滯留、三酸甘油脂上升、輕度血壓變化；口服因首渡效應，靜脈血栓/肺栓塞風險在高危族群更需評估。',
    refs:[{name:'Endocrine Society 2017', url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },
  {
    id:'ev_inj',
    class:'HRT-激素',
    rx:'RX',
    name:'戊酸雌二醇（Estradiol valerate）注射劑',
    aliases:['EV','17β-雌二醇戊酸酯'],
    forms:'肌肉注射',
    typicalDose:'5–20 mg 每 1–2 週（依醫囑與濃度調整）',
    bioavailability:'近乎 100%（肌注）',
    metabolism:'注射後緩釋→酯酶水解為 E2；肝臟 CYP3A4 部分代謝並經 UGT 結合；腸肝循環。',
    enzymeInhibition:'無臨床顯著抑制/誘導；為 CYP/UGT 受質，強誘導劑可能略降暴露。',
    halfLife:'釋放/表觀半衰期約 3–5 天；作用可達 7–14 天（與劑量相關）。',
    actions:'原本用於雌激素替代治療；跨性別女性 HRT 中提供穩定雌激素濃度，抑制睪固酮、促進女性第二性徵。',
    indications:'更年期症候群、卵巢功能衰竭、性別肯定治療。',
    monitoring:'E2 濃度、肝功能、血脂、凝血因子。',
    cautions:'與口服相比峰值較高，需避免過高劑量引發副作用。',
    interactions:'酵素誘導劑對肌注影響小。',
    sideEffects:'注射部位疼痛/硬結、週期性濃度峰值相關不適（潮熱、頭痛、情緒起伏）、乳房脹痛、水腫；全身性與雌激素相同（VTE 風險仍需評估，但較少首渡肝效應）。',
    refs:[{name:'Endocrine Society 2017', url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },
  {
    id:'micronized_prog',
    class:'HRT-激素',
    rx:'RX',
    name:'微粒化黃體酮（Micronized progesterone）口服膠囊',
    aliases:['天然黃體酮'],
    forms:'口服/陰道膠囊',
    typicalDose:'100–200 mg 睡前（依醫囑）',
    bioavailability:'約 10%（口服，首過代謝高）',
    metabolism:'肝臟 CYP3A4/2C19 為主，並有還原/硫酸化/葡萄醣醛酸化途徑；腎/膽排。',
    enzymeInhibition:'無臨床顯著 CYP 抑制；為 CYP3A4 受質，酵素誘導劑可↓濃度。',
    halfLife:'約 5–20 小時（配方/個體差異）。',
    actions:'原本用於黃體不足、不孕治療；跨性別女性 HRT 中可能改善乳腺發育、助眠、情緒穩定（證據有限）。',
    indications:'黃體不足、不孕治療、部分跨性別輔助療程。',
    monitoring:'嗜睡、頭暈；與鎮靜藥併用留意。',
    cautions:'肝功能不良需評估；嗜睡者建議睡前服用。',
    interactions:'鎮靜安眠藥會增加嗜睡風險。',
    sideEffects:'嗜睡、頭暈、夢境生動/翌日賴床、情緒低落或易怒、乳房脹痛、水腫、頭痛；少數人胃口不適。',
    refs:[{name:'UCSF TransCare', url:'https://transcare.ucsf.edu/guidelines'}]
  },
  {
    id:'drospirenone_ethinylestradiol',
    class:['HRT-激素','HRT-抗雄'],
    rx:'RX',
    name:'屈螺酮／炔雌醇（Drospirenone / Ethinylestradiol）口服錠',
    aliases:['屈螺酮＋炔雌醇','DRSP/EE','Drospirenone + EE','避孕藥複方'],
    forms:'口服錠',
    typicalDose:'每日 1 錠（多為 21/7 或 24/4 方案，依品項與醫囑）',
    bioavailability:'EE：~38–48%；DRSP：~76–85%',
    metabolism:'DRSP 主要經 CYP3A4；EE 經 CYP3A4/2C9/2C19、UGT 與硫酸化，腸肝循環明顯。',
    enzymeInhibition:'EE 可抑制 CYP1A2/UGT（臨床意義有限）；兩者皆為 CYP3A4 受質，強抑制/誘導劑顯著影響濃度；DRSP 亦為 P-gp 受質。',
    halfLife:'EE ~13–27 小時；DRSP ~30–35 小時。',
    actions:'原本用於避孕與經前症候群；DRSP 具抗雄性與輕度利尿（抗醛固酮），EE 為合成雌激素。跨性別女性中可作為雌激素補充與抗雄輔助（多為離標籤、需評估風險）。',
    indications:'口服避孕；部分場合作為跨女性之輔助雌激素/抗雄（離標籤）。',
    monitoring:'血壓、血栓風險因子、鉀離子（特別合併保鉀藥時）、肝功能、頭痛/偏頭痛史。',
    cautions:'含 EE 的複方相較 17β-雌二醇製劑具較高 VTE 風險；吸菸且年齡≥35 歲禁忌。腎功能差或合併螺內酯/ACEI/ARB 需留意高鉀。',
    interactions:'CYP3A4 誘導劑（如某些抗癲癇藥、利福平）可降低療效；與含鉀利尿劑/保鉀藥合用可能升高血鉀；與抗凝藥需評估出血/血栓風險。',
    sideEffects:'噁心、乳房脹痛、頭痛/偏頭痛、情緒波動、點滴出血、血壓上升；VTE 風險增加（特別具危險因子者）。DRSP 成分可能導致高鉀（心悸、乏力）。',
    refs:[
      {name:'產品仿單（各品牌）', url:'#'},
      {name:'UCSF TransCare', url:'https://transcare.ucsf.edu/guidelines'}
    ]
  },

  /* ==== HRT-抗雄類 ==== */
  {
    id:'spironolactone',
    class:'HRT-抗雄',
    rx:'RX',
    name:'螺內酯（Spironolactone）口服錠',
    aliases:['安體舒通'],
    forms:'口服錠',
    typicalDose:'50–200 mg/日（依血鉀與效果調整）',
    bioavailability:'約 60–90%',
    metabolism:'肝臟代謝（CYP3A4 參與）→ 活性代謝物如 canrenone；腎排為主。',
    enzymeInhibition:'輕度 P-gp 抑制；對主要 CYP 影響有限；為 CYP3A4 受質。',
    halfLife:'母藥 ~1.4 小時；canrenone ~16–18 小時。',
    actions:'原本為利尿降壓藥（醛固酮拮抗）；跨性別女性 HRT 中抑制雄激素作用與分泌。',
    indications:'高血壓、心衰、水腫；跨性別抗雄。',
    monitoring:'血鉀、腎功能、血壓。',
    cautions:'腎功能不全或高鉀禁用。',
    interactions:'保鉀利尿劑、ACEI/ARB、NSAIDs 增加高鉀風險。',
    sideEffects:'多尿、低血壓/頭暈、嗜睡、噁心、乳房不適、月經不規則/點滴出血；高血鉀（心悸、乏力、四肢麻木）與腎功能惡化（需監測）。',
    refs:[{name:'UCSF TransCare', url:'https://transcare.ucsf.edu/guidelines'}]
  },
  {
    id:'bicalutamide',
    class:'HRT-抗雄',
    rx:'RX',
    name:'比卡魯胺（Bicalutamide）口服錠',
    aliases:[],
    forms:'口服錠',
    typicalDose:'25–50 mg/日（依醫囑）',
    bioavailability:'幾乎完全吸收',
    metabolism:'肝臟大量代謝（氧化/葡萄醣醛酸化，CYP3A4 為主）；糞/尿排泄。',
    enzymeInhibition:'可抑制 CYP3A4（弱–中度）；與華法林（CYP2C9 受質）可能交互作用，需監測 INR。',
    halfLife:'~6 天（R-對映體最活性，半衰期長）。',
    actions:'原本用於攝護腺癌（雄激素受體拮抗）；跨性別女性 HRT 中抑制雄激素作用（離標籤使用）。',
    indications:'攝護腺癌、跨性別抗雄（非核准適應症）。',
    monitoring:'肝功能。',
    cautions:'肝毒性風險高，必須定期驗血。',
    interactions:'肝酵素代謝藥物可能影響其濃度。',
    sideEffects:'肝功能異常/黃疸、噁心、潮熱、乳房不適或壓痛、皮疹、疲倦；罕見嚴重肝毒性需立即就醫。',
    refs:[{name:'臨床經驗', url:'#'}]
  },

  /* ==== HRT-阻斷劑 ==== */
  {
    id:'gnrh_analogue',
    class:'HRT-阻斷劑',
    rx:'RX',
    name:'GnRH 類比（亮丙瑞林、曲普瑞林）長效注射',
    aliases:['青春期阻斷劑'],
    forms:'長效肌注',
    typicalDose:'每 1–3 個月注射一次（依醫囑）',
    bioavailability:'接近 100%',
    metabolism:'胜肽類藥物，經組織/血中胜肽酶降解；非 CYP 途徑。',
    enzymeInhibition:'不抑制/誘導 CYP；交互作用以藥效學為主。',
    halfLife:'母體血漿半衰期數小時，但長效劑型釋放期間為 1–3 個月。',
    actions:'原本用於性早熟、荷爾蒙依賴型腫瘤；跨性別女性 HRT 中可抑制睪固酮分泌。',
    indications:'性早熟、乳癌、攝護腺癌、青春期抑制。',
    monitoring:'E2/T 濃度、骨密度、代謝指標。',
    cautions:'長期使用注意骨質疏鬆。',
    interactions:'臨床顯著交互作用少。',
    sideEffects:'潮熱、出汗、性慾下降、情緒波動/易怒、頭痛、注射部位反應；長期可見骨密度下降、關節痠痛。',
    refs:[{name:'Endocrine Society 2017', url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },

  /* ==== 精麻類 ==== */
{
  id:'quetiapine',
  class:'精麻類',
  rx:'RX',
  name:'喹硫平（Quetiapine）口服錠／緩釋錠',
  aliases:['Seroquel','第二代抗精神病藥'],
  forms:'IR 口服錠／XR 緩釋錠',
  typicalDose:'IR：150–750 mg/日；XR：300–800 mg/日（依適應症）',
  bioavailability:'~9%（首渡效應高）',
  metabolism:'肝臟 CYP3A4 主要代謝；代謝物多為無活性。',
  enzymeInhibition:'非顯著抑制；為 3A4 受質（強抑/誘劑需調整劑量）。',
  halfLife:'~6–7 小時；XR 釋放延長暴露。',
  actions:'多巴胺 D2、血清素 5-HT2A 拮抗；具抗組織胺與抗膽鹼活性。',
  indications:'思覺失調、雙相躁／鬱期、重鬱增效（XR）',
  monitoring:'嗜睡、姿勢性低血壓、體重與代謝（血糖/血脂）、QT 風險',
  cautions:'嗜睡與代謝異常常見；起始與加量期注意暈眩與跌倒風險',
  interactions:'CYP3A4 抑制/誘導藥、酒精與中樞抑制劑相加',
  sideEffects:'嗜睡、口乾、體重增加、頭暈、便秘、低血壓',
  refs:[{name:''}]
},
{
  id:'risperidone',
  class:'精麻類',
  rx:'RX',
  name:'利培酮（Risperidone）口服錠／口溶錠',
  aliases:['Risperdal','第二代抗精神病藥'],
  forms:'口服錠/OD 錠/口服液；長效針劑（醫療）',
  typicalDose:'1–6 mg/日（分次或一次）',
  bioavailability:'~70%',
  metabolism:'肝臟 CYP2D6（主要）與 3A4 代謝為 9-OH-risperidone（具活性）。',
  enzymeInhibition:'自身不顯著抑制；為 2D6／3A4 受質（強抑/誘劑需調整）。',
  halfLife:'母藥 ~3 小時；活性總量（含代謝物）~20 小時',
  actions:'多巴胺 D2、血清素 5-HT2A 拮抗；亦作用於 α1、H1 受體',
  indications:'思覺失調、雙相躁期、兒童／青少年自閉症易怒',
  monitoring:'錐體外症狀、泌乳上升、體重代謝、QT',
  cautions:'錐體外症狀與泌乳異常較其他 SGA 稍高',
  interactions:'2D6 抑制劑（如 fluoxetine、paroxetine）升濃度；中樞抑制劑相加',
  sideEffects:'錐體外症狀、嗜睡、體重增加、頭暈、泌乳增加',
  refs:[{name:''}]
},
{
  id:'milnacipran',
  class:'精麻類',
  rx:'RX',
  name:'鹽酸米那普侖片（Milnacipran）',
  aliases:['SNRI'],
  forms:'口服錠',
  typicalDose:'50–200 mg/日，分 2 次（依適應症與耐受）',
  bioavailability:'~85–90%',
  metabolism:'肝代謝較少；主要經腎排泄（未經大量 CYP 代謝）。',
  enzymeInhibition:'非顯著 CYP 抑制/誘導；與強腎毒性或升血壓藥需留意。',
  halfLife:'~6–8 小時',
  actions:'選擇性 5-HT 與 NE 再攝取抑制（SNRI）',
  indications:'重鬱症（部分地區適應症）；纖維肌痛（部分地區）',
  monitoring:'血壓、心率、焦慮失眠、腎功能（需調整劑量）',
  cautions:'與 MAOI 併用禁忌；注意血壓上升與排尿困難',
  interactions:'其他血清素作用藥有血清素症風險；酒精/中樞抑制劑加成',
  sideEffects:'噁心、出汗、失眠或嗜睡、心悸、口乾',
  refs:[{name:''}]
},
{
  id:'zopiclone',
  class:'精麻類',
  rx:'RX',
  name:'佐匹克隆片（Zopiclone）',
  aliases:['Z-drug','安眠藥'],
  forms:'口服錠',
  typicalDose:'成人 3.75–7.5 mg 眠前',
  bioavailability:'~80%',
  metabolism:'肝臟主要經 CYP3A4（及 2C8）代謝；代謝物多無活性。',
  enzymeInhibition:'自身非顯著抑制；為 3A4 受質（強抑/誘劑需調整）。',
  halfLife:'~5 小時',
  actions:'作為 GABA-A 受體促效（與苯二氮平位點相關）',
  indications:'短期失眠治療',
  monitoring:'隔日殘效、認知/駕駛能力、呼吸抑制風險（合併中樞抑制劑）',
  cautions:'可能導致複雜睡行為（夢遊、夢駕）；避免酒精同用；老年降低劑量',
  interactions:'酒精、鴉片類、中樞抑制劑相加；強 3A4 抑制/誘導改變濃度',
  sideEffects:'苦味、嗜睡、頭暈、口乾、協調受損',
  refs:[{name:''}]
},
{
  id:'olanzapine',
  class:'精麻類',
  rx:'RX',
  name:'奧氮平（Olanzapine）口服錠／口溶錠',
  aliases:['Zyprexa','第二代抗精神病藥'],
  forms:'口服錠/OD 錠；長效針劑（醫療）',
  typicalDose:'5–20 mg/日（依適應症）',
  bioavailability:'~60%',
  metabolism:'肝臟 UGT1A4 葡萄醛酸化與 CYP1A2（次要 2D6）代謝。',
  enzymeInhibition:'自身不顯著抑制；為 1A2 受質（抽菸/1A2 誘導↓濃度）。',
  halfLife:'~30 小時（個體差異大）',
  actions:'多巴胺 D2、血清素 5-HT2A 拮抗；H1、M1 活性較強（易鎮靜與代謝影響）',
  indications:'思覺失調、雙相躁期／維持、重鬱增效（與 fluoxetine 合併）',
  monitoring:'體重、血糖、血脂、鎮靜、抗膽鹼副作用',
  cautions:'代謝風險較高（體重/血糖/血脂）；避免與注射鎮靜劑併用導致過度鎮靜',
  interactions:'吸菸/1A2 誘導↓濃度；1A2 抑制↑濃度；中樞抑制劑相加',
  sideEffects:'嗜睡、體重增加、食慾↑、口乾、便秘、姿勢性低血壓',
  refs:[{name:''}]
},
  {
    id:'sertraline',
    class:'精麻類',
    rx:'RX',
    name:'舍曲林（Sertraline）口服錠',
    aliases:['左洛復'],
    forms:'口服錠',
    typicalDose:'50–200 mg/日（依醫囑）',
    bioavailability:'約 44%',
    metabolism:'肝臟代謝（CYP2B6/2C19/2D6/3A4 參與），並經脫甲基/結合；代謝物腎排。',
    enzymeInhibition:'中度抑制 CYP2D6，弱抑制 2B6/2C19；為多酵素受質。',
    halfLife:'~26 小時；去甲代謝物 ~62–104 小時。',
    actions:'原本用於憂鬱症、焦慮症（SSRI）；跨性別者常用於伴隨焦慮或憂鬱的輔助治療。',
    indications:'憂鬱症、焦慮症、PTSD。',
    monitoring:'情緒變化、自傷念頭、副作用。',
    cautions:'勿與 MAOI 併用；起效需數週。',
    interactions:'與其他血清素增強藥併用有血清素症候群風險。',
    sideEffects:'噁心、腹瀉、食慾改變、失眠或嗜睡、口乾、手抖、初期焦慮短暫惡化、性功能影響；罕見血清素症候群（躁動、發燒、肌強直）。',
    refs:[{name:'', }]
  },
  {
    id:'melatonin',
    class:'精麻類',
    rx:'OTC',
    name:'褪黑激素（Melatonin）口服錠',
    aliases:['退黑激素'],
    forms:'口服錠／滴劑',
    typicalDose:'1–3 mg 睡前（依地區法規）',
    bioavailability:'口服變異大（約 15–30%）',
    metabolism:'肝臟 CYP1A2 主要代謝，亦有硫酸化/葡萄醣醛酸化；腎排。',
    enzymeInhibition:'無臨床顯著抑制；為 CYP1A2 受質（咖啡因/吸菸等可影響）。',
    halfLife:'~30–50 分鐘（速釋）。',
    actions:'原本用於時差、失眠；跨性別者可能用於改善睡眠品質。',
    indications:'短期失眠、時差反應。',
    monitoring:'白天嗜睡。',
    cautions:'部分國家屬處方藥；孕哺期請詢問醫師。',
    interactions:'與鎮靜藥併用增加嗜睡。',
    sideEffects:'嗜睡、頭暈、頭痛、清晨倦怠、夢境生動/惡夢；偶見胃口或情緒輕度改變。',
    refs:[{name:'',}]
  },
  {
    id:'psilocybin',
    class:'精麻類',
    rx:'RX',
    name:'裸蓋菇素（Psilocybin）口服膠囊/粉末',
    aliases:['神奇蘑菇活性成分'],
    forms:'口服膠囊/粉末',
    typicalDose:'臨床試驗劑量 10–25 mg（不可自行使用）',
    bioavailability:'約 50%',
    metabolism:'去磷酸化為 psilocin；psilocin 主要經 MAO-A 與 UGT（UGT1A10 等）代謝；腎排。',
    enzymeInhibition:'無臨床顯著 CYP 抑制/誘導資料；與 MAOI 合用具藥效學風險。',
    halfLife:'psilocin ~2–3 小時。',
    actions:'原本研究用於抗藥性憂鬱症、臨終焦慮；跨性別者可望用於改善嚴重情緒困擾（尚屬研究階段）。',
    indications:'研究中（憂鬱症、焦慮症等）。',
    monitoring:'心理狀態變化；需專業人員監測。',
    cautions:'在大部分國家屬管制物質；不可自行服用。',
    interactions:'與其他致幻劑或精神藥併用風險未知。',
    sideEffects:'感知與情緒顯著改變、焦慮/恐慌、血壓/心率上升、噁心嘔吐；可能誘發或加劇精神症狀—僅限臨床研究監督。',
    refs:[{name:'Johns Hopkins Psychedelic Research', url:'https://hopkinspsychedelic.org/'}]
  },
  {
    id:'fluvoxamine',
    class:'精麻類',
    rx:'RX',
    name:'马来酸氟伏沙明（Fluvoxamine Maleate）口服 劑型',
    aliases:['Fluvoxamine','Luvox'],
    forms:'口服錠',
    typicalDose:'50–300 mg/日（依適應症與醫囑調整）',
    bioavailability:'約 50–53%（口服首過代謝後）',
    metabolism:'肝臟代謝（主要 CYP2D6/1A2/2C19/3A4 參與）；腎排為主。',
    enzymeInhibition:'強抑 CYP1A2；中度抑 CYP2C19/3A4，亦抑 2D6——交互作用多。',
    halfLife:'~15–26 小時（長期使用可延長）。',
    actions:'SSRI，抑制血清素再吸收、具 σ-1 受體激動性，提升血清素濃度並具抗焦慮作用',
    indications:'強迫症（OCD）、重性憂鬱症、恐慌症、社交焦慮、PTSD，有研究用於 COVID-19 初期高風險門診以降低惡化',
    monitoring:'情緒改善、焦慮、GI不適、肝功能、以及與 CYP 交互作用的其他藥物效果',
    cautions:'對 CYP1A2 劑量影響大，需注意藥物交互作用；老年或肝功能差需劑量調整；勿與 MAOI 合用',
    interactions:'強抑 CYP1A2、中度抑 CYP2C19、CYP3A4；可增加如奧氮平、苯二氮䓬類代謝物血中濃度，聯合使用需降低劑量；與 SSRIs 聯用可能有血清素症候群風險。',
    sideEffects:'便秘、頭痛、焦慮、易怒、性功能障礙、口乾、睡眠障礙、GI不適，停止用藥易有撤藥症狀；較少心血管不良反應',
    refs:[
      {name:'Clinical Pharmacokinetics of Fluvoxamine (van Harten et al., 1995)',url:'https://pubmed.ncbi.nlm.nih.gov/8846617/'},
      {name:'Luvox (Fluvoxamine Maleate) FDA label',url:'https://www.accessdata.fda.gov/drugsatfda_docs/label/2007/021519lbl.pdf'},
      {name:'Wikipedia – Fluvoxamine',url:'https://en.wikipedia.org/wiki/Fluvoxamine'}
    ]
  },
  {
    id:'lithium',
    class:'精麻類',
    rx:'RX',
    name:'碳酸鋰（Lithium Carbonate）緩釋片',
    aliases:['Lithium SR','鋰鹽'],
    forms:'口服錠（緩釋）',
    typicalDose:'400–1200 mg/日，分 1–2 次（依血中濃度與醫囑調整）',
    bioavailability:'近 100%（口服吸收完全，無蛋白結合）',
    metabolism:'不經肝代謝；腎小管重吸收，經腎臟排泄。',
    enzymeInhibition:'無 CYP 抑制/誘導；與腎功能與鈉平衡密切相關。',
    halfLife:'~18–36 小時（高齡/腎功差可延長）。',
    actions:'作用機制未完全明確，主要影響鈉、鉀通道與第二信使系統；可穩定情緒，預防躁鬱症躁期與鬱期發作',
    indications:'雙相情感障礙（躁症急性期、維持治療）、重性憂鬱症增效治療、情緒不穩定相關疾病',
    monitoring:'血中鋰濃度（治療範圍 0.6–1.2 mmol/L）、腎功能（BUN/Cr）、甲狀腺功能、電解質；建議初期每週監測，穩定後每 3–6 個月',
    cautions:'治療窗狹窄，需嚴格監測；腎功能不全、高齡、脫水或合併利尿劑、NSAIDs、ACEI/ARB 需謹慎；孕婦禁用（致畸性心臟缺陷風險）',
    interactions:'利尿劑、NSAIDs、ACEI/ARB 可升高鋰濃度並增加中毒風險；咖啡因與茶鹼可能降低鋰濃度；合併抗精神病藥增加錐體外副作用風險',
    sideEffects:'手抖、口渴、多尿、多飲、體重增加、腸胃不適、甲狀腺功能低下；長期使用可能導致腎功能損害；中毒症狀包含嘔吐、震顫、共濟失調、意識混亂，嚴重可致昏迷或死亡',
    refs:[
      {name:'UpToDate – Lithium: Drug Information',url:'https://www.uptodate.com/contents/lithium-drug-information'},
      {name:'FDA Label – Lithium Carbonate',url:'https://www.accessdata.fda.gov/drugsatfda_docs/label/2018/017812s040lbl.pdf'}
    ]
  },
  {
    id:'quetiapine',
    class:'精麻類',
    rx:'RX',
    name:'奎硫平（Quetiapine）',
    aliases:['思瑞康','Seroquel'],
    forms:'口服錠（一般釋放、緩釋劑型）',
    typicalDose:'一般 150–800 mg/日，依病情分 1–2 次；失眠或輔助用途時可用低劑量（25–100 mg/日）',
    bioavailability:'口服吸收佳，蛋白結合率約 83%，經肝臟 CYP3A4 代謝',
    metabolism:'CYP3A4 為主，生成 norquetiapine 等；腎/糞排。',
    enzymeInhibition:'本身不顯著抑制主要 CYP；為 CYP3A4 受質，與抑/誘劑交互作用顯著。',
    halfLife:'IR ~6 小時；norquetiapine ~12 小時；XR 依釋放機構延長吸收相。',
    actions:'拮抗多巴胺 D2、血清素 5-HT2A 受體，並作用於 H1、α1 受體；具鎮靜、抗躁、抗憂鬱、抗精神病作用',
    indications:'思覺失調症、雙相情感障礙（躁期、鬱期、維持治療）、重性憂鬱症增效治療、部分失眠與焦慮症（非核准適應症）',
    monitoring:'體重、BMI、血糖、血脂、血壓；肝功能（ALT/AST）；必要時做心電圖（QT 間期）',
    cautions:'慎用於心血管疾病、糖尿病或代謝症候群患者；避免與強效 CYP3A4 抑制劑/誘導劑併用；老年失智相關精神病禁用（增加死亡風險）',
    interactions:'CYP3A4 抑制劑（如酮康唑、紅黴素）會升高血中濃度；CYP3A4 誘導劑（如卡馬西平、苯妥英）會降低療效；合併中樞抑制劑會加強嗜睡',
    sideEffects:'嗜睡、體重增加、代謝異常（血糖升高、血脂異常）、姿勢性低血壓、口乾、便秘；高劑量可能增加錐體外症狀與 QT 延長',
    refs:[
      {name:'UpToDate – Quetiapine: Drug Information',url:'https://www.uptodate.com/contents/quetiapine-drug-information'},
      {name:'FDA Label – Seroquel (Quetiapine)',url:'https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/020639s069,021472s053lbl.pdf'}
    ]
  },

  /* ==== HRT-激素（新增）==== */
  {
    id:'progesterone_inj',
    class:'HRT-激素',
    rx:'RX',
    name:'黃體酮（Progesterone）注射液（油劑）',
    aliases:['天然黃體酮 注射劑'],
    forms:'肌肉注射（油劑）',
    typicalDose:'依醫囑；婦產科常見 25–50 mg IM 每 2–3 日。跨性別用途為個別化、證據有限。',
    bioavailability:'接近 100%（IM）',
    metabolism:'肝臟 CYP3A4/2C19 參與代謝；亦有還原/結合途徑；腎/膽排。',
    enzymeInhibition:'無顯著 CYP 抑制；為 CYP 受質，強誘導劑可↓濃度。',
    halfLife:'約 10–20 小時；油劑庫存效應使作用時間延長。',
    actions:'原本用於黃體不足、助孕與月經異常；跨性別女性 HRT 中偶作輔助（睡眠、情緒、乳腺發育之體感，證據有限）。',
    indications:'黃體不足、助孕治療；跨性別治療屬個別化考量。',
    monitoring:'嗜睡、頭暈、注射部位疼痛；肝功能（長期）。',
    cautions:'非首選；油劑注射需無菌操作，避免自行施打；嗜睡者建議夜間使用。',
    interactions:'與鎮靜安眠藥合用增加嗜睡；與某些抗癲癇酵素誘導劑可能降低效力。',
    sideEffects:'注射部位疼痛/硬塊、嗜睡、頭暈、情緒低落、乳房脹痛、水腫；少數人頭痛或皮疹。',
    refs:[{name:'UCSF TransCare', url:'https://transcare.ucsf.edu/guidelines'}]
  },

  /* ==== HRT-抗雄（新增）==== */
  {
    id:'cyproterone_acetate',
    class:'HRT-抗雄',
    rx:'RX',
    name:'醋酸環丙孕酮（Cyproterone acetate, CPA）口服錠',
    aliases:['CPA'],
    forms:'口服錠',
    typicalDose:'12.5–50 mg/日（用最低有效劑量；依醫囑與副作用調整）',
    bioavailability:'約 88–95%',
    metabolism:'肝臟 CYP3A4 為主，並有還原/結合代謝；腎/膽排。',
    enzymeInhibition:'抑制 CYP2C9（顯著）與 CYP3A4（中度）；可能與華法林等交互作用。',
    halfLife:'約 2–3 天（文獻 1.6–4.3 天不等）。',
    actions:'原本為抗雄＋具黃體素作用；跨性別女性 HRT 中抑制睪固酮分泌與作用。',
    indications:'攝護腺相關治療、性慾過強治療；跨性別抗雄（部分地區常用）。',
    monitoring:'肝功能（ALT/AST）、泌乳素、情緒狀態；長期／高累積劑量注意腦膜瘤風險。',
    cautions:'肝毒性、情緒低落、泌乳素升高；高累積劑量與腦膜瘤風險關聯，需定期追蹤、評估停藥或降劑量。',
    interactions:'與肝臟酵素相關藥物交互作用；與其他致嗜睡藥合用需小心。',
    sideEffects:'嗜睡/倦怠、情緒低落、性慾下降、體重上升、泌乳素升高、肝功能異常；長期或高累積劑量與腦膜瘤風險相關（需定期追蹤）。',
    refs:[{name:'歐洲藥管局安全通報（CPA 與腦膜瘤）', url:'#'}]
  },

  /* ==== 精麻類（新增）==== */
  {
    id:'lidocaine_hcl_inj',
    class:'精麻類',
    rx:'RX',
    name:'鹽酸利多卡因（Lidocaine HCl）注射液',
    aliases:['局部麻醉劑'],
    forms:'浸潤/神經阻滯注射（常見 0.5% / 1% / 2%）',
    typicalDose:'臨床人員操作。最大劑量（保守值）：不含腎上腺素 ≤ 4.5 mg/kg（上限約 300 mg）；含腎上腺素 ≤ 7 mg/kg（上限約 500 mg）。',
    bioavailability:'局部注射以局麻為主；系統性吸收視部位/血流而異',
    metabolism:'肝臟 CYP1A2 與 CYP3A4 為主，生成 MEGX/GX；腎排。',
    enzymeInhibition:'自身對 CYP 影響小；為 1A2/3A4 受質，肝血流/抑制劑可↑濃度。',
    halfLife:'~1.5–2 小時（靜注）；末端相依給藥方式變化。',
    actions:'原本用於小手術/縫合/牙科之局部麻醉；不具精神治療適應症。',
    indications:'局部麻醉、神經阻滯、抗心律不整（靜注需加護監測）。',
    monitoring:'注射時觀察毒性：口唇麻、耳鳴、意識混亂、抽搐、心律異常；需備脂肪乳應急。',
    cautions:'務必由醫療專業人員操作，嚴禁自行注射；末梢血供差的部位避免與腎上腺素併用。',
    interactions:'與其他局麻藥或抗心律藥物併用增加毒性風險。',
    sideEffects:'局麻毒性：口唇/舌麻、金屬味、耳鳴、頭暈、抽搐、意識混亂、心律異常；嚴重者可呼吸抑制/心搏停止（必須由醫療人員操作）。',
    refs:[{name:'臨床麻醉學參考', url:'#'}]
  },
  {
    id:'alprazolam',
    class:'精麻類',
    rx:'RX',
    name:'阿普唑仑（Alprazolam）口服錠',
    aliases:['Xanax','苯二氮䓬'],
    forms:'口服錠/OD 錠',
    typicalDose:'0.25–1 mg，每日 2–3 次（短期、最低有效劑量；依醫囑）',
    bioavailability:'約 80–90%',
    metabolism:'肝臟 CYP3A4 主要代謝；代謝物腎排。',
    enzymeInhibition:'自身不抑制主要 CYP；為 CYP3A4 受質（抑制劑↑、誘導劑↓濃度）。',
    halfLife:'約 11–15 小時（高齡者可延長）。',
    actions:'原本用於焦慮/恐慌障礙（BZD）；跨性別族群若合併焦慮，可由精神科短期使用。',
    indications:'焦慮症、恐慌症（短期）。',
    monitoring:'嗜睡、認知影響、跌倒風險；評估依賴/離斷症狀。',
    cautions:'有依賴與離斷風險，勿自行增減/停藥；避免酒精與其他中樞抑制劑。',
    interactions:'與酒精、鴉片類、鎮靜安眠藥合用會疊加呼吸抑制風險。',
    sideEffects:'嗜睡、頭暈、記憶力與反應下降、共濟不良；依賴與離斷症狀（反跳焦慮、失眠）；與酒精或鴉片類併用可致呼吸抑制。',
    refs:[{name:'精神藥理學指引', url:'#'}]
  },

  {
    id:'estradiol_benzoate_inj',
    class:'HRT-激素',
    rx:'RX',
    name:'苯甲酸雌二醇（Estradiol benzoate, EB）注射液',
    aliases:['EB','17β-雌二醇苯甲酸酯'],
    forms:'肌肉注射（油劑）',
    typicalDose:'5–10 mg IM 每 3–7 日一次（依醫囑調整；跨性別 HRT 多用較低頻高穩定方案）',
    bioavailability:'接近 100%（IM）',
    metabolism:'油劑緩釋→酯酶水解為 E2；後續經 CYP3A4/UGT 代謝與腸肝循環。',
    enzymeInhibition:'無顯著抑制；為 CYP/UGT 受質。',
    halfLife:'表觀半衰期 ~1–2 天；作用通常 2–5 天。',
    actions:'原本用於雌激素缺乏（更年期症狀、卵巢切除後等）；跨性別女性 HRT 中補充雌激素，促進女性第二性徵並抑制 LH/FSH。',
    indications:'雌激素缺乏、更年期症狀、卵巢切除後治療；跨性別女性/非二元者 HRT。',
    monitoring:'E2、肝功能、血脂、凝血風險因子；注射部位觀察。',
    cautions:'有血栓風險者需謹慎；手術前是否停藥依醫囑。',
    interactions:'酵素誘導劑（如部分抗癲癇藥、利福平）可能降低血中濃度。',
    sideEffects:'注射部位疼痛/硬結、乳房脹痛、頭痛、潮熱、水腫；整體雌激素相關風險仍含 VTE（需評估個人危險因子）。',
    refs:[{name:'Endocrine Society Guideline', url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },
  {
    id:'estradiol_oral_sg',
    class:'HRT-激素',
    rx:'RX',
    name:'雌二醇（Estradiol）口服錠',
    aliases:['E2','17β-雌二醇'],
    forms:'口服錠',
    typicalDose:'1–4 mg/日，分 1–2 次（跨性別 HRT 劑量依醫囑調整）',
    bioavailability:'約 5%（口服；肝臟首渡效應明顯）',
    metabolism:'CYP3A4/1A2/2C9/2C19 參與；UGT 與硫酸化結合；腸肝循環顯著。',
    enzymeInhibition:'無臨床顯著抑制；為 CYP/UGT 受質。',
    halfLife:'母體 E2 ~1–2 小時；表觀作用較投與頻率而定。',
    actions:'原本用於更年期症狀、卵巢功能減退等雌激素缺乏；跨性別女性 HRT 補充雌激素並抑制 LH/FSH，促進女性第二性徵。',
    indications:'更年期症狀、卵巢切除後雌激素補充；跨性別女性/非二元者 HRT。',
    monitoring:'E2、肝功能、血脂；留意血栓風險因子。',
    cautions:'肝功能差、高血栓風險者需審慎使用；注意劑量與首渡效應。',
    interactions:'酵素誘導劑（部分抗癲癇藥、利福平等）可能降低血中濃度。',
    sideEffects:'胃腸不適、乳房脹痛、頭痛、情緒波動、水腫、血脂（特別 TG）上升；口服因首渡效應，VTE 風險在高危族群更需注意。',
    refs:[{name:'新加坡 HSA 藥品資料庫', url:'https://www.hsa.gov.sg/' }]
  },

  /* ==== HRT－雄激素（FTM/跨男性/指定女性出生的非二元者）==== */
  {
    id:'testosterone_enanthate_im',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮庚酸酯（Testosterone enanthate）注射液',
    aliases:['TE','庚酸睪酮'],
    forms:'肌肉注射（油劑）',
    typicalDose:'50–100 mg IM 每週 或 100–200 mg IM 每 2 週（依醫囑與濃度調整）',
    bioavailability:'≈100%（IM）',
    metabolism:'酯酶水解為睪固酮；後續以 17β-HSD/3α-HSD 還原與 UGT2B17 結合；腎/膽排。',
    enzymeInhibition:'不抑制主要 CYP；為 UGT2B17/酵素受質；與強誘導/抑制劑交互作用有限。',
    halfLife:'釋放/表觀半衰期約 4–5 天；作用 1–2 週。',
    actions:'原適應症為男性性腺機能低下的睪固酮替代；跨男性 HRT 提供生理範圍 T 值，促進男性第二性徵（聲變低、毛髮增多、肌量↑），抑制月經。',
    indications:'男性性腺機能低下；跨男性/指定女性出生之非二元者之性別肯定治療。',
    monitoring:'總/游離 T（注射谷/峰）、血比容/血紅素、脂質、肝腎功能、血壓；依需要追蹤月經抑制與情緒/痤瘡。',
    cautions:'紅血球增多症風險（血比容＞54% 需處置/調整劑量）；痤瘡、掉髮、睡眠呼吸中止症惡化、情緒起伏；孕期禁用。',
    interactions:'與華法林等抗凝劑可能交互影響；與糖皮質激素/利尿劑併用留意水腫。',
    sideEffects:'痤瘡/皮脂增多、多毛、體味改變、聲音變低（不可逆）、性慾變化、注射部位痛；紅血球/血比容上升、水腫、情緒起伏/易怒、脫髮；睡眠呼吸中止症惡化。',
    refs:[{name:'Endocrine Society 2017', url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },
  {
    id:'testosterone_cypionate_im',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮環戊丙酸酯（Testosterone cypionate）注射液',
    aliases:['TC','環戊丙酸睪酮'],
    forms:'肌肉注射（油劑）',
    typicalDose:'50–100 mg IM 每週 或 100–200 mg IM 每 2 週',
    bioavailability:'≈100%（IM）',
    metabolism:'同 TE；UGT2B17 結合為主，腎/膽排。',
    enzymeInhibition:'不抑制主要 CYP；為 UGT 受質。',
    halfLife:'約 4–8 天（表觀）；作用 1–2 週。',
    actions:'與 TE 類似之長效酯；跨男性 HRT 維持生理 T 值、誘導男性化改變。',
    indications:'男性性腺機能低下；跨男性 HRT。',
    monitoring:'同 TE。',
    cautions:'同 TE；部分人對溶媒（棉籽油/苄醇等）敏感需留意。',
    interactions:'同 TE。',
    sideEffects:'同 TE：痤瘡、多毛、紅血球增多、情緒起伏、脫髮、注射部位反應；少數人對溶媒成分（如棉籽油/苄醇）敏感。',
    refs:[{name:'WPATH/處方慣例彙整', url:'https://www.wpath.org'}]
  },
  {
    id:'testosterone_undecanoate_depot',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮十一酸酯（Testosterone undecanoate）長效肌注',
    aliases:['TU depot','Nebido® 等'],
    forms:'深部肌注（油劑，長效）',
    typicalDose:'1000 mg IM 起始後 6 週再打一針，之後每 10–14 週（依濃度與症狀調整）',
    bioavailability:'≈100%（IM）',
    metabolism:'酯酶水解→T；後續同 T（UGT2B17 主要）。',
    enzymeInhibition:'不抑制主要 CYP；為 UGT 受質。',
    halfLife:'端端相 ~20–34 天；臨床作用 10–14 週。',
    actions:'極長效釋放維持穩定 T；跨男性 HRT 可減少濃度波動與針次。',
    indications:'男性性腺機能低下；跨男性 HRT。',
    monitoring:'與其他注射型相同；注意峰值期紅血球上升。',
    cautions:'注射量大需深部肌注；油栓風險極低但需遵循給藥規範；孕期禁用。',
    interactions:'同類雄激素製劑相近。',
    sideEffects:'同類雄激素副作用；注射量大需深部肌注，極罕見油栓/過敏反應（依投藥規範監測）。',
    refs:[{name:'製品仿單/臨床經驗', url:'#'}]
  },
  {
    id:'testosterone_gel_1pct',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮凝膠 1%（Transdermal gel）',
    aliases:['Testogel®/AndroGel®（依地區品牌）'],
    forms:'外用凝膠（每日塗抹）',
    typicalDose:'50–100 mg（以原藥量計）QD 外用；依血中 T 調整',
    bioavailability:'約 10–15%（經皮）',
    metabolism:'皮膚吸收→系統循環後與 TE/TC 相同（UGT2B17 結合為主）；腎/膽排。',
    enzymeInhibition:'不抑制主要 CYP；為 UGT 受質。',
    halfLife:'表觀 ~12–24 小時（每日塗抹維持穩定）。',
    actions:'原為男性性腺機能低下替代；跨男性 HRT 維持較平穩 T，避免注射峰谷差。',
    indications:'男性性腺機能低下；跨男性 HRT。',
    monitoring:'血中 T（塗抹後 2–8 小時抽血較一致）、血比容/血紅素、肝腎功能、脂質；避免皮膚轉移污染家人。',
    cautions:'塗抹區乾燥後再接觸他人；避免接觸女性/孩童；易燃溶劑遠離火源；孕期禁用。',
    interactions:'經皮系統性交互作用較少；與外用類固醇並用時留意皮膚刺激。',
    sideEffects:'局部皮膚刺激/紅癢、痤瘡、多毛；紅血球增多；藥物轉移污染他人風險（接觸女性/孩童後可致不良反應）。',
    refs:[{name:'UCSF TransCare', url:'https://transcare.ucsf.edu/guidelines'}]
  },
  {
    id:'testosterone_patch',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮貼片（Transdermal patch）',
    aliases:[],
    forms:'經皮貼片（晚間貼、隔日換或每日換，依品項）',
    typicalDose:'2.5–7.5 mg/24h（可多片併用以達標）',
    bioavailability:'受貼片設計影響（持續釋放）',
    metabolism:'系統性後同 T（UGT2B17 結合）；腎/膽排。',
    enzymeInhibition:'不抑制主要 CYP；為 UGT 受質。',
    halfLife:'表觀 ~24 小時（持續釋放；移除後濃度在 24 小時內下降）。',
    actions:'原為男性低 T 替代；跨男性 HRT 提供平穩 T。',
    indications:'男性性腺機能低下；跨男性 HRT（對凝膠不耐或偏好貼片者）。',
    monitoring:'同經皮製劑；留意貼附性與皮膚刺激。',
    cautions:'皮膚刺激/接觸性皮炎；黏貼位置需輪替。',
    interactions:'系統性交互作用少。',
    sideEffects:'貼片處紅斑/刺激/接觸性皮炎、瘙癢或脫落；全身性副作用同其他雄激素（痤瘡、多毛、紅血球增多等）。',
    refs:[{name:'產品仿單', url:'#'}]
  },
  {
    id:'testosterone_undecanoate_oral',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮十一酸酯口服膠囊（Oral TU）',
    aliases:['Andriol®/Jatenzo®（配方差異）'],
    forms:'口服膠囊（需與餐/高脂膳食同服）',
    typicalDose:'依配方 80–237 mg BID（Jatenzo®）或依仿單調整',
    bioavailability:'高度受餐脂影響（變異大）',
    metabolism:'腸道/淋巴吸收後酯酶水解→T；後續 UGT2B17 結合；部分經 CYP 少量代謝。',
    enzymeInhibition:'不抑制主要 CYP；為 UGT 受質。',
    halfLife:'表觀 ~3–6 小時（配方相關，需分次）。',
    actions:'原為低 T 替代；跨男性 HRT 可用但血中濃度變異較大、肝指數與血壓需留意。',
    indications:'男性性腺機能低下；跨男性 HRT（次選）。',
    monitoring:'血中 T、肝功能、血壓、血比容。',
    cautions:'生體可用率變動大；部分配方與高脂餐同服才穩；孕期禁用。',
    interactions:'與強誘導/抑制 CYP 或 P-gp 藥物可能影響濃度；與脂溶性藥物共同影響吸收。',
    sideEffects:'血壓上升（部分配方有警示）、肝功能指數升高、胃腸不適、頭痛、痤瘡、紅血球增多；濃度變異較大。',
    refs:[{name:'處方資料與臨床經驗', url:'#'}]
  },

  /* ==== 經皮雌激素 ==== */
  {
    id:'estradiol_patch',
    class:'HRT-激素',
    rx:'RX',
    name:'雌二醇貼片（Estradiol transdermal patch）',
    aliases:['17β-雌二醇貼片'],
    forms:'經皮貼片',
    typicalDose:'常見 25–100 μg/日（每週更換 1–2 次，依醫囑）',
    bioavailability:'~90%（避開首渡代謝）',
    metabolism:'系統性後以 CYP3A4/1A2 部分代謝並經 UGT/SULT 結合；腸肝循環。',
    enzymeInhibition:'無顯著抑制；為 CYP/UGT 受質。',
    halfLife:'表觀 ~13–20 小時；移除貼片後 24 小時內濃度顯著下降。',
    actions:'原本用於治療停經後雌激素不足；跨性別女性作為主要雌激素補充，促進女性第二性徵並抑制睪固酮。',
    indications:'更年期症狀、骨質疏鬆預防、跨女性/非二元 HRT。',
    monitoring:'E2 濃度、肝功能、血脂、皮膚反應。',
    cautions:'避免貼在受損皮膚；貼片可能引起皮膚過敏。',
    interactions:'酵素誘導劑影響較小；與抗凝藥併用留意出血風險。',
    sideEffects:'貼附處紅斑、搔癢、刺激或接觸性皮炎；乳房脹痛、頭痛、輕度水腫；相較口服，對肝脂質與凝血的影響較小但 VTE 風險仍需個別評估。',
    refs:[{name:'Endocrine Society 2017', url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },
  {
    id:'estradiol_gel',
    class:'HRT-激素',
    rx:'RX',
    name:'雌二醇凝膠（Estradiol gel）',
    aliases:['17β-雌二醇凝膠'],
    forms:'經皮凝膠',
    typicalDose:'0.75–3 mg E2 含量/日（依醫囑塗抹）',
    bioavailability:'~82%（避開首渡代謝）',
    metabolism:'同貼片：CYP3A4/1A2 部分代謝＋UGT/SULT 結合；腸肝循環。',
    enzymeInhibition:'無顯著抑制；為 CYP/UGT 受質。',
    halfLife:'表觀 ~12–24 小時（每日塗抹維持）。',
    actions:'原本用於更年期雌激素替代；跨性別女性作為經皮雌激素選擇之一，血中濃度平穩。',
    indications:'更年期症狀、骨質疏鬆預防、跨女性/非二元 HRT。',
    monitoring:'E2、肝功能、血脂；觀察皮膚刺激。',
    cautions:'塗抹部位需乾燥；避免與他人皮膚接觸。',
    interactions:'與其他外用藥併用可能影響吸收率。',
    sideEffects:'塗抹處紅癢/刺激、輕度乾燥；乳房脹痛、頭痛、輕度水腫；若未待乾燥即接觸他人，可能造成藥物轉移。',
    refs:[{name:'UCSF TransCare', url:'https://transcare.ucsf.edu/guidelines'}]
  },
  {
    id:'estradiol_spray',
    class:'HRT-激素',
    rx:'RX',
    name:'雌二醇經皮噴霧（Estradiol spray）',
    aliases:['17β-雌二醇噴霧'],
    forms:'經皮噴霧劑',
    typicalDose:'1–3 噴/日（每噴含約 1.53 mg E2，依醫囑）',
    bioavailability:'~85%（避開首渡代謝）',
    metabolism:'同經皮製劑：CYP3A4 部分代謝＋UGT/SULT 結合；腸肝循環。',
    enzymeInhibition:'無顯著抑制；為 CYP/UGT 受質。',
    halfLife:'表觀 ~12–24 小時。',
    actions:'原本用於更年期雌激素補充；跨性別女性可作為經皮給藥選擇，方便控制劑量。',
    indications:'更年期症狀、骨質疏鬆預防、跨女性/非二元 HRT。',
    monitoring:'E2 濃度、肝功能、皮膚反應。',
    cautions:'避免接觸眼睛與黏膜；塗抹後需等待乾燥。',
    interactions:'與其他外用製劑併用需間隔時間。',
    sideEffects:'局部刺激/紅斑、乾燥或灼熱感；乳房脹痛、頭痛；若未乾燥即接觸他人皮膚，可能導致藥物轉移。',
    refs:[{name:'產品仿單', url:'#'}]
  },

  /* ==== HRT-抗雄（5α-還原酶抑制劑）==== */
  {
    id:'finasteride_1mg',
    class:'HRT-抗雄',
    rx:'RX',
    name:'非那雄胺 1 mg（Finasteride）口服錠',
    aliases:['Fina','1 mg 劑型'],
    forms:'口服錠',
    typicalDose:'1 mg QD（多用於雄性禿；跨女性常作輔助降 DHT）',
    bioavailability:'約 65%',
    metabolism:'肝臟 CYP3A4 為主；代謝物腎/糞排。',
    enzymeInhibition:'自身非顯著 CYP 抑制；為 CYP3A4 受質（強抑/誘劑影響有限）。',
    halfLife:'~5–6 小時（高齡 ~8 小時）。',
    actions:'5α-還原酶 II 型抑制劑，降低睪固酮轉為 DHT；跨女性 HRT 可作輔助以減少頭皮/體毛 DHT 作用（單用對總睪固酮抑制有限）。',
    indications:'雄性禿；跨女性/非二元者作 DHT 降低之輔助（離標籤使用）。',
    monitoring:'PSA（會下降約 50%，解讀需校正）、毛髮變化、性功能與情緒評估。',
    cautions:'孕婦/可孕者避免接觸碎片粉末（致畸胎風險）；性功能與情緒變化少數報告需留意。',
    interactions:'與無明顯嚴重交互作用為主；合併其他降 PSA 藥物時解讀 PSA 更需小心。',
    sideEffects:'性慾降低、勃起/射精困難、精液量減少、乳房不適或腫塊（罕見）、皮疹；少數人報告情緒低落/焦慮。',
    refs:[{name:'產品仿單 / 臨床經驗', url:'#'}]
  },
  {
    id:'finasteride_5mg',
    class:'HRT-抗雄',
    rx:'RX',
    name:'非那雄胺 5 mg（Finasteride）口服錠',
    aliases:['Fina','5 mg 劑型'],
    forms:'口服錠',
    typicalDose:'5 mg QD（原適應症前列腺肥大；跨性別用途依醫囑個別化）',
    bioavailability:'約 65%',
    metabolism:'同 1 mg（CYP3A4 為主）。',
    enzymeInhibition:'自身非顯著 CYP 抑制；為 CYP3A4 受質。',
    halfLife:'~5–6 小時（高齡 ~8 小時）。',
    actions:'同上，劑量較高；臨床對毛髮影響與 1 mg 類似，前列腺體積影響較明顯。',
    indications:'良性前列腺肥大；（離標籤）跨性別 DHT 輔助抑制。',
    monitoring:'PSA、泌尿症狀、性功能/情緒變化。',
    cautions:'同 1 mg；長期使用需與醫師討論風險效益。',
    interactions:'同 1 mg。',
    sideEffects:'同 1 mg；偶見頭暈、疲倦。',
    refs:[{name:'產品仿單 / 臨床經驗', url:'#'}]
  },
  {
    id:'dutasteride_0_5mg',
    class:'HRT-抗雄',
    rx:'RX',
    name:'度他雄胺 0.5 mg（Dutasteride）軟膠囊',
    aliases:['Duta'],
    forms:'口服軟膠囊',
    typicalDose:'0.5 mg QD',
    bioavailability:'約 60%',
    metabolism:'肝臟 CYP3A4/3A5 參與；代謝物腎/糞排。',
    enzymeInhibition:'自身不顯著抑制；為 CYP3A4 受質，強抑制劑可↑濃度。',
    halfLife:'~5 週（很長）。',
    actions:'5α-還原酶 I/II 型皆抑制，DHT 降幅較非那雄胺大；跨女性可作 DHT 輔助抑制（單用對總睪固酮抑制有限）。',
    indications:'良性前列腺肥大；（離標籤）雄性禿、跨性別 DHT 輔助抑制。',
    monitoring:'PSA（顯著下降，解讀需校正）、肝功能（少數）、性功能/情緒評估。',
    cautions:'孕婦/可孕者避免接觸內容物；半衰期長（約 5 週），停藥後作用消退較慢。',
    interactions:'CYP3A4 強抑制劑可能增加其濃度（理論上）。',
    sideEffects:'性慾降低、勃起/射精困難、乳房不適、皮疹；偶見頭暈、胃口不適；少數報告情緒低落。',
    refs:[{name:'產品仿單 / 臨床經驗', url:'#'}]
  },

  /* ==== HRT－激素（其他劑型補充）==== */
  {
    id:'testosterone_nasal_gel',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮鼻用凝膠（Transdermal nasal gel）',
    aliases:['鼻用 T 凝膠'],
    forms:'鼻腔凝膠',
    typicalDose:'一側鼻孔 1 次量 x 兩側，每日 2–3 次（依品項，總日劑量約 22–33 mg 原藥）',
    bioavailability:'經鼻吸收（避免首渡；短時峰谷，需多次給藥）',
    metabolism:'吸收後同 T（UGT2B17 結合為主）；局部少量吞嚥亦經肝代謝。',
    enzymeInhibition:'不抑制主要 CYP；為 UGT 受質。',
    halfLife:'表觀 ~10–12 小時（需每日 2–3 次給藥維持）。',
    actions:'男性低 T 替代；跨男性 HRT 可用於偏好非注射且不適合經皮軟膏者，血中 T 波動較頻繁。',
    indications:'男性性腺機能低下；跨男性/AFAB 非二元者 HRT（個別化）。',
    monitoring:'血中 T（給藥後 1–2 小時抽血以評估峰值區間）、血比容/血紅素、血壓、肝腎功能、脂質。',
    cautions:'鼻黏膜刺激/鼻炎史者謹慎；需固定時段分次使用以減波動；孕期禁用。',
    interactions:'鼻用局部製劑同用可能影響吸收。',
    sideEffects:'鼻黏膜刺激、流鼻水/結痂、頭痛；系統性仍可能出現痤瘡、多毛、紅血球增多、情緒起伏等。',
    refs:[{name:'產品仿單 / 臨床經驗', url:'#'}]
  },
  {
    id:'testosterone_pellet_implant',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮皮下植入丸（Pellet implant）',
    aliases:['Testopel® 等'],
    forms:'皮下植入（每顆常見 75 mg）',
    typicalDose:'總量 450–900 mg 每 3–6 個月（依濃度與症狀調整）',
    bioavailability:'持續釋放（近乎 100%）',
    metabolism:'緩慢釋放後同 T；UGT2B17 結合為主。',
    enzymeInhibition:'不抑制主要 CYP；為 UGT 受質。',
    halfLife:'裝置為長期零階釋放，無固定單一 t½；臨床作用期約 3–6 個月。',
    actions:'長期緩釋維持較平穩 T；跨男性 HRT 可減少注射頻率與濃度波動。',
    indications:'男性性腺機能低下；跨男性 HRT（取決於地區可近性）。',
    monitoring:'血中 T（植入後 4–6 週與之後週期性監測）、血比容/血紅素、脂質、肝腎功能。',
    cautions:'需小手術植入；移位/擠出與感染風險低但存在；孕期禁用。',
    interactions:'系統性交互作用與其他 T 類似。',
    sideEffects:'局部瘀青/疼痛/感染、植入物擠出；系統性：痤瘡、多毛、紅血球增多、水腫、情緒變化、脫髮等。',
    refs:[{name:'產品仿單 / 臨床經驗', url:'#'}]
  },
  {
    id:'testosterone_sc_autoinject',
    class:'HRT－激素',
    rx:'RX',
    name:'睪固酮庚酸酯週投自動注射（SC auto-injector）',
    aliases:['週投皮下注射 T'],
    forms:'皮下注射（預充填自動注射筆）',
    typicalDose:'50 / 75 / 100 mg SC 每週（依濃度與症狀調整）',
    bioavailability:'≈100%（SC）',
    metabolism:'吸收後同 TE/TC；UGT2B17 結合為主。',
    enzymeInhibition:'不抑制主要 CYP；為 UGT 受質。',
    halfLife:'表觀 ~4–5 天（週投設計）。',
    actions:'與 IM 注射相似；皮下固定每週給藥，濃度較平穩、操作便利。',
    indications:'男性性腺機能低下；跨男性 HRT。',
    monitoring:'血中 T（谷/峰）、血比容/血紅素、血壓、脂質、肝腎功能；注射部位反應。',
    cautions:'避免於皮膚感染/疤痕區注射；孕期禁用。',
    interactions:'與抗凝劑並用需留意注射處出血；其他同類雄激素相近。',
    sideEffects:'注射處紅腫/硬塊、痤瘡、多毛、紅血球增多、水腫、情緒起伏、頭痛；少數人血壓上升。',
    refs:[{name:'產品仿單 / 臨床經驗', url:'#'}]
  },

  /* ==== 精麻類（新增）==== */
  {
    id:'escitalopram',
    class:'精麻類',
    rx:'RX',
    name:'艾司西酞普蘭（Escitalopram）口服錠',
    aliases:['來士普','Lexapro'],
    forms:'口服錠/滴劑',
    typicalDose:'10–20 mg/日（憂鬱/焦慮；依醫囑）',
    bioavailability:'~80%',
    metabolism:'肝臟 CYP2C19、2D6、3A4 代謝；代謝物腎排。',
    enzymeInhibition:'弱抑 CYP2D6；為多酵素受質（2C19/2D6/3A4）。',
    halfLife:'~27–32 小時。',
    actions:'SSRI，提升血清素；常用於重鬱與焦慮障礙，跨性別族群合併情緒症狀時常見處方。',
    indications:'重性憂鬱症、廣泛性焦慮、社交焦慮、恐慌症等',
    monitoring:'情緒、自傷風險、失眠/嗜睡、性功能副作用',
    cautions:'勿與 MAOI 併用；起效需 2–4 週；青少年初期需留意不安/激越',
    interactions:'與其他血清素能藥物並用增血清素症候群風險；CYP2C19 抑制/誘導劑影響濃度',
    sideEffects:'噁心、腹瀉、失眠/嗜睡、口乾、性功能影響；罕見 QT 延長',
    refs:[{name:'FDA/仿單',url:'#'}]
  },
  {
    id:'fluoxetine',
    class:'精麻類',
    rx:'RX',
    name:'氟西汀（Fluoxetine）口服膠囊/錠',
    aliases:['百憂解','Prozac'],
    forms:'口服錠/膠囊',
    typicalDose:'20–60 mg/日（依病情）',
    bioavailability:'~72%',
    metabolism:'肝臟 CYP2D6 為主，並有 2C9/2C19/3A4 參與；生成 norfluoxetine。',
    enzymeInhibition:'強抑 CYP2D6；中度抑制 2C19/3A4——交互作用多。',
    halfLife:'母藥 ~2–4 天；norfluoxetine ~7–15 天（極長）。',
    actions:'SSRI，半衰期長；對嗜睡或體重增加顧慮者較友善',
    indications:'重性憂鬱、強迫症、經前不悅、神經性暴食等',
    monitoring:'情緒變化、焦慮激越、體重',
    cautions:'與 MAOI、噻哌啶類間需清除期；可能致失眠',
    interactions:'CYP2D6 強抑制；與三環抗鬱、抗精神病藥交互作用多',
    sideEffects:'噁心、失眠、焦慮、頭痛、性功能影響；罕見血清素症候群',
    refs:[{name:'FDA/仿單',url:'#'}]
  },
  {
    id:'clonazepam',
    class:'精麻類',
    rx:'RX',
    name:'氯硝西泮（Clonazepam）口服錠',
    aliases:['利福全','Klonopin','苯二氮䓬'],
    forms:'口服錠/OD 錠',
    typicalDose:'0.25–2 mg/日 分次（短期/依醫囑）',
    bioavailability:'≈90%',
    metabolism:'肝臟 CYP3A4 代謝為主；代謝物腎排。',
    enzymeInhibition:'自身不抑制主要 CYP；為 CYP3A4 受質。',
    halfLife:'~20–50 小時。',
    actions:'BZD，抗焦慮、抗癲癇；短期緩解恐慌/嚴重焦慮',
    indications:'恐慌症、某些癲癇',
    monitoring:'嗜睡、跌倒、依賴與離斷症狀',
    cautions:'避免長期規律使用；勿與酒精/鴉片併用',
    interactions:'中樞抑制劑疊加呼吸抑制；CYP3A4 抑制/誘導影響濃度',
    sideEffects:'嗜睡、頭暈、記憶與反應下降、協調障礙；依賴風險',
    refs:[{name:'精神藥理學指引',url:'#'}]
  },
  {
    id:'diazepam',
    class:'精麻類',
    rx:'RX',
    name:'地西泮（Diazepam）口服錠/注射液',
    aliases:['安定','Valium','苯二氮䓬'],
    forms:'口服錠、肌/靜注（醫療）',
    typicalDose:'2–10 mg 每日 1–4 次（短期，依醫囑）',
    bioavailability:'>90%',
    metabolism:'肝臟 CYP2C19 與 3A4 代謝→去甲地西泮等活性代謝物。',
    enzymeInhibition:'自身不顯著抑制；為 3A4/2C19 受質（抑/誘劑影響濃度）。',
    halfLife:'母藥 ~20–50 小時；去甲代謝物 ~50–100 小時（很長）。',
    actions:'BZD，抗焦慮、抗痙攣、鎮靜；半衰期長',
    indications:'焦慮、酒精離斷、肌痙攣等',
    monitoring:'嗜睡、認知/跌倒風險、依賴',
    cautions:'與酒精/鴉片類併用危險；老年慎用',
    interactions:'中樞抑制劑疊加、CYP3A4/2C19 交互作用',
    sideEffects:'嗜睡、運動失調、記憶力下降；依賴、離斷症狀',
    refs:[{name:'FDA/仿單',url:'#'}]
  },
  {
    id:'zolpidem',
    class:'精麻類',
    rx:'RX',
    name:'佐匹克隆（Zolpidem）口服錠',
    aliases:['安眠藥 Z 類','Stilnox/Ambien'],
    forms:'口服錠/緩釋',
    typicalDose:'5–10 mg HS（短期失眠）',
    bioavailability:'~70%',
    metabolism:'肝臟 CYP3A4 為主，並有 1A2/2D6 少量參與；腎排。',
    enzymeInhibition:'自身不顯著抑制；為 CYP3A4 受質（抑/誘劑影響）。',
    halfLife:'~2–3 小時（女性稍長）。',
    actions:'非 BZD 睡眠誘導劑，作用於 GABA_A',
    indications:'短期失眠',
    monitoring:'殘餘嗜睡、夢遊/異常行為',
    cautions:'避免與酒精/中樞抑制劑併用；駕駛作業隔日注意',
    interactions:'中樞抑制劑疊加；CYP3A4 抑制劑升高濃度',
    sideEffects:'嗜睡、頭暈、健忘、夜間行為異常；依賴風險較低但存在',
    refs:[{name:'FDA/仿單',url:'#'}]
  },
  {
    id:'methylphenidate_ir',
    class:'精麻類',
    rx:'RX',
    name:'哌甲酯（Methylphenidate）速釋錠',
    aliases:['利他能','Ritalin','中樞興奮劑'],
    forms:'口服錠/緩釋劑型',
    typicalDose:'IR 5–20 mg 每日 2–3 次；ER 18–72 mg QD（ADHD/依醫囑）',
    bioavailability:'~30%（配方差異）',
    metabolism:'主要由肝臟酯酶 CES1 水解為 ritalinic acid（非 CYP）；腎排。',
    enzymeInhibition:'不抑制主要 CYP；為 CES1 受質（基因型可影響）。',
    halfLife:'IR ~2–3 小時；ER 視劑型 3–7 小時。',
    actions:'阻斷去甲腎上腺素與多巴胺再攝取；提升專注',
    indications:'注意力不足過動症（ADHD），嗜睡症',
    monitoring:'心率/血壓、食慾/體重、睡眠、情緒',
    cautions:'心血管疾病、焦慮/妄想傾向者謹慎；有濫用潛勢',
    interactions:'MAOI 禁忌；與升壓藥、SSRI/抗精神病藥需評估',
    sideEffects:'食慾下降、失眠、心悸、焦慮、頭痛；罕見心血管事件',
    refs:[{name:'FDA/仿單',url:'#'}]
  },
  {
    id:'atomoxetine',
    class:'精麻類',
    rx:'RX',
    name:'原甲狀腺素回收抑制劑－托莫西汀（Atomoxetine）',
    aliases:['Strattera','非興奮劑 ADHD 藥'],
    forms:'口服膠囊',
    typicalDose:'0.5–1.2 mg/kg/日 或 40–100 mg/日（成人）',
    bioavailability:'~63%',
    metabolism:'肝臟 CYP2D6 為主（廣泛/差代謝者差異大）；代謝物腎排。',
    enzymeInhibition:'自身不顯著抑制；為 2D6 受質，強抑制劑（如氟西汀）↑暴露。',
    halfLife:'廣泛代謝者 ~5 小時；差代謝者 ~20 小時。',
    actions:'選擇性去甲腎上腺素再吸收抑制；非中樞興奮劑',
    indications:'ADHD',
    monitoring:'血壓/心率、肝功能、情緒/自殺意念',
    cautions:'肝毒性罕見通報；青少年初期監測情緒',
    interactions:'CYP2D6 抑制劑↑濃度；與升壓藥併用留意 BP',
    sideEffects:'食慾下降、失眠、口乾、噁心、頭痛；少數肝指數升高',
    refs:[{name:'FDA/仿單',url:'#'}]
  },
  {
    id:'lamotrigine',
    class:'精麻類',
    rx:'RX',
    name:'拉莫三嗪（Lamotrigine）口服錠',
    aliases:['Lamictal','心境穩定劑/抗癲癇'],
    forms:'口服錠/咀嚼錠/OD 錠',
    typicalDose:'緩慢上調至 100–200 mg/日（雙相鬱期維持；依醫囑）',
    bioavailability:'≈98%',
    metabolism:'肝臟以 UGT1A4 葡萄醣醛酸化為主；腎排。',
    enzymeInhibition:'不抑制 CYP；受 UGT 抑制劑（如丙戊酸）↑濃度、酵素誘導劑↓濃度。',
    halfLife:'~25–33 小時（合併丙戊酸可至 ~60 小時；與誘導劑 ~14 小時）。',
    actions:'抑制鈉通道；雙相鬱期預防復發證據佳',
    indications:'癲癇、雙相情感障礙（鬱期預防）',
    monitoring:'皮疹（SJS/TEN）、肝腎功能、情緒',
    cautions:'起始需緩升以降低嚴重皮疹風險；與丙戊酸合用需大幅降劑量',
    interactions:'丙戊酸↑濃度；酶誘導劑↓濃度',
    sideEffects:'頭暈、視複、噁心、皮疹（罕見重症）',
    refs:[{name:'臨床指引',url:'#'}]
  },
  {
    id:'aripiprazole',
    class:'精麻類',
    rx:'RX',
    name:'阿立哌唑（Aripiprazole）口服錠',
    aliases:['Abilify','第二代抗精神病藥'],
    forms:'口服錠/OD 錠/注射長效劑（醫療）',
    typicalDose:'5–30 mg/日（依適應症）',
    bioavailability:'~87%',
    metabolism:'肝臟 CYP2D6 與 3A4 代謝；生成去氫代謝物（具活性）。',
    enzymeInhibition:'自身不顯著抑制；為 2D6/3A4 受質（強抑/誘劑需調劑量）。',
    halfLife:'~75 小時；去氫代謝物 ~94 小時。',
    actions:'多巴胺 D2/血清素 5-HT1A 部分致效、5-HT2A 拮抗；體重代謝影響較小',
    indications:'思覺失調、雙相障礙、重鬱增效、妥瑞氏症',
    monitoring:'焦躁不安、失眠、衝動控制、代謝指標',
    cautions:'可能誘發靜坐不能；青少年留意衝動行為',
    interactions:'CYP3A4/2D6 抑制/誘導需要調劑量',
    sideEffects:'失眠、焦躁、噁心、頭暈；代謝影響較低但仍需監測',
    refs:[{name:'FDA/仿單',url:'#'}]
  },

  /* ==== 雌激素／相關（新增）==== */
  {
    id:'estradiol_cypionate_inj',
    class:'HRT-激素',
    rx:'RX',
    name:'雌二醇環戊丙酸酯（Estradiol cypionate, EC）注射液',
    aliases:['EC','17β-雌二醇環戊丙酸酯'],
    forms:'肌肉注射（油劑）',
    typicalDose:'2–10 mg IM 每 1–2 週（依醫囑與濃度調整）',
    bioavailability:'≈100%（IM）',
    metabolism:'緩釋後酯酶水解→E2；後續 CYP3A4/UGT 代謝。',
    enzymeInhibition:'無顯著抑制；為 CYP/UGT 受質。',
    halfLife:'表觀 ~5–8 天；作用 1–2 週。',
    actions:'長效雌二醇酯；HRT 中維持 E2 濃度、抑制 LH/FSH',
    indications:'雌激素替代、性別肯定治療',
    monitoring:'E2、肝功能、血脂、VTE 風險因子；注射部位',
    cautions:'高血栓風險個案評估；避免過高峰值',
    interactions:'酵素誘導劑可能降低暴露量（相對口服影響較小）',
    sideEffects:'注射痛、乳房脹痛、頭痛、潮熱、水腫；評估個別 VTE 風險',
    refs:[{name:'Endocrine Society Guideline',url:'https://www.endocrine.org/clinical-practice-guidelines/gender-dysphoria-gender-incongruence'}]
  },
  {
    id:'conjugated_estrogens_oral',
    class:'HRT-激素',
    rx:'RX',
    name:'結合型雌激素（Conjugated estrogens）口服錠',
    aliases:['CEE','Premarin® 類'],
    forms:'口服錠',
    typicalDose:'0.3–1.25 mg/日（更年期 HRT；跨性別使用依醫囑）',
    bioavailability:'成分混合，口服吸收良好',
    metabolism:'多種雌激素的硫酸鹽/葡萄醣醛酸鹽混合物；肝代謝＋腸肝循環，UGT/SULT 為主，部分 CYP 參與。',
    enzymeInhibition:'自身不明顯抑制；為 UGT/SULT/CYP 受質。',
    halfLife:'成分多樣，半衰期不一（大致 12–24 小時區間）。',
    actions:'多種馬雌固酮/雌三醇結合物；作為雌激素補充',
    indications:'更年期症狀；（跨性別 HRT 次線選擇）',
    monitoring:'E2/E1（參考）、肝功能、脂質、VTE 風險',
    cautions:'口服對肝脂質/凝血影響較經皮顯著',
    interactions:'與誘導劑/抗凝劑等交互作用需評估',
    sideEffects:'胃口不適、乳房脹痛、頭痛、水腫；VTE 風險依個體而異',
    refs:[{name:'產品仿單/臨床經驗',url:'#'}]
  },
  {
    id:'ethinyl_estradiol_note',
    class:'HRT-激素',
    rx:'RX',
    name:'炔雌醇（Ethinyl estradiol, EE）—不建議做 GAHT 主力',
    aliases:['EE'],
    forms:'口服錠（多見於避孕藥複方）',
    typicalDose:'避孕配方依仿單；GAHT 中一般**不建議**作主力雌激素',
    bioavailability:'高',
    metabolism:'肝臟 CYP3A4/2C9/2C19 代謝，並經 UGT/SULT 結合；腸肝循環強烈。',
    enzymeInhibition:'可抑制 CYP1A2 與 UGT（程度視劑量）；為 CYP3A4 受質。',
    halfLife:'~13–27 小時。',
    actions:'合成雌激素，肝臟效應與 VTE 風險相對較高',
    indications:'口服避孕（複方）；GAHT 中僅特殊情況評估',
    monitoring:'若使用：血壓、血脂、VTE 風險因子',
    cautions:'跨性別 HRT 建議優先使用 17β-雌二醇製劑（口服/經皮/注射）',
    interactions:'與多種藥物有代謝交互作用',
    sideEffects:'與雌激素類似但凝血/肝效應更顯著',
    refs:[{name:'WPATH/Endocrine Society 建議',url:'#'}]
  },
  {
    id:'estriol_topical',
    class:'HRT-激素',
    rx:'RX',
    name:'雌三醇（Estriol, E3）陰道凝膠/乳膏',
    aliases:['E3'],
    forms:'局部陰道/皮膚外用',
    typicalDose:'（陰道）0.5 mg 每日→每週 2–3 次維持；依仿單',
    bioavailability:'局部吸收為主，全身暴露低',
    metabolism:'肝臟結合代謝（UGT/SULT）；腸肝循環部分參與。',
    enzymeInhibition:'無臨床顯著 CYP 抑制；為 UGT/SULT 受質。',
    halfLife:'~6–9 小時（全身暴露極低）。',
    actions:'弱效雌激素，改善泌尿生殖道萎縮/乾澀',
    indications:'泌尿生殖道症候群（停經後）',
    monitoring:'局部刺激、出血；全身暴露低通常無需抽血',
    cautions:'尚非 GAHT 主力；子宮存在者長期高劑量需評估內膜風險',
    interactions:'少見',
    sideEffects:'局部刺激/灼熱、分泌物改變；全身副作用少',
    refs:[{name:'產品仿單',url:'#'}]
  },
  {
    id:'estetrol_oral',
    class:'HRT-激素',
    rx:'RX',
    name:'雌四醇（Estetrol, E4）口服錠',
    aliases:['天然胎盤來源雌激素'],
    forms:'口服錠（部分地區核可與 DRSP 複方避孕）',
    typicalDose:'避孕配方 15 mg E4 + DRSP；單方 HRT 劑量依地區資料',
    bioavailability:'口服佳',
    metabolism:'以 UGT/SULT 結合代謝為主，CYP 參與相對較少；腎/糞排。',
    enzymeInhibition:'無明顯 CYP 抑制；為 UGT/SULT 受質（資料仍在累積）。',
    halfLife:'~24–32 小時。',
    actions:'選擇性雌激素活性，對肝/凝血影響可能較 EE 低；GAHT 應用資料仍有限',
    indications:'口服避孕（部分國家）；更年期 HRT（部分地區）',
    monitoring:'E2/E4 濃度資料有限；依臨床與風險因子評估',
    cautions:'跨性別 HRT 證據尚少，屬個別化與研究中的選擇',
    interactions:'CYP 相關交互作用相對少見（資料仍在累積）',
    sideEffects:'與雌激素相似：乳房脹痛、頭痛、噁心；VTE 風險資料仍在累積',
    refs:[{name:'近年文獻與仿單',url:'#'}]
  }
];