name = 'yinnlimnascloud'
main = "src/worker.js"
compatibility_date = "2025-03-03"

assets = { directory = "./yinn", binding = "ASSETS" }
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
workers_dev = false
