name = "yinnlimnascloud"
main = "src/worker.js"
compatibility_date = "2025-03-03"

# 直接從 ./yinn 提供靜態檔（不經 KV）
assets = { directory = "./yinn", binding = "ASSETS" }

workers_dev = false

[observability.logs]
enabled = true

# 綁域名的路由（也可以只填一個）
routes = ["yinnlimnas.store/*", "www.yinnlimnas.store/*"]
